### ISSUE TITLE
<= Error in 'sub': Protocol message SetDesc has no "trusted" field. 

### ISSUE THREAD

**Issue by gabriel-vasile** [tinode/chat#725] opened 2022-02-17 11:06 UTC

**Comment by or-else** [comment] 2022-02-18 17:22
Not sure what exactly this refers to, but I've updated gRPC-related stuff in devel and will release it in 0.18.1

**Comment by or-else** [comment] 2022-02-19 03:26
0.18.1 is released. I cannot verify if the problem is fixed because this issue has no meaningful description. Closing.

**Closed by or-else** 2022-02-19 03:26 UTC
Labels: incomplete
