### ISSUE TITLE
Change owner in group topic

### ISSUE THREAD

**Issue by wmshek1992** [tinode/chat#418] opened 2020-04-14 04:28 UTC
### Subject of the issue
Change owner in group topic

Hi, 

I am trying to transfer the ownership of a group topic and then leave it. 
I was doing it by using {set}

`{
    "set": {
        "id": "118229",
        "topic": "grpqF-Sk_oD-jQ",
        "sub": {
            "user": "usrE-6UDy41emE",
            "mode":"JRWPASDO"
        }
    }
}`

but code=304 was received. 
`{"ctrl":{"id":"118229","topic":"grpqF-Sk_oD-jQ","code":304,"text":"not modified","ts":"2020-04-14T04:22:02.852Z"}}`

I also realised that the target user did not want "O" in "acs"

` {
                "updated": "2020-04-14T03:41:02.072Z",
                "online": true,
                "acs": {
                    "mode": "JRWPASD",
                    "given": "JRWPASDO",
                    "want": "JRWPASD"
                },
                "read": 2,
                "recv": 2,
                "user": "usrE-6UDy41emE"
            }`

Is there anything else I have to do to transfer the ownership?

**Comment by or-else** [comment] 2020-04-14 05:42
I think you've gotten 304 because it was the second time you've sent the message. You've gotten 200 the first time you sent it. 

The person must accept the ownership before it's actually transferred.

**Comment by wmshek1992** [comment] 2020-04-14 07:09
Thanks for your response.

Yes, you are right. I removed "O" and added it back. It returned 200.

The user is given "O"
`{"pres":{"topic":"grpqF-Sk_oD-jQ","src":"usrE-6UDy41emE","what":"acs","act":"usrw2g_kxhlL-0","dacs":{"given":"+O"}}} `

But in {meta}, mode is still JRWPASD. What should I do for the person to accept the ownership?

`{
    "meta": {
        "id": "82353",
        "topic": "grpqF-Sk_oD-jQ",
        "ts": "2020-04-14T07:04:16.450Z",
        "sub": [
            {
                "updated": "2020-04-14T01:40:45.254Z",
                "online": true,
                "acs": {
                    "mode": "JRWPASDO",
                    "given": "JRWPASDO",
                    "want": "JRWPASDO"
                },
                "read": 2,
                "recv": 2,
                "user": "usrw2g_kxhlL-0"
            },
            {
                "updated": "2020-04-14T03:41:02.072Z",
                "online": true,
                "acs": {
                    "mode": "JRWPASD",
                    "given": "JRWPASDO",
                    "want": "JRWPASD"
                },
                "read": 2,
                "recv": 2,
                "user": "usrE-6UDy41emE"
            }
        ]
    }
}`

**Comment by or-else** [comment] 2020-04-14 10:17
As I said earlier, the person you gave the `O` permission to must accept it by sending something like `{ "set": { "id": "123", "topic": "grpqF-Sk_oD-jQ", "sub": { "mode":"JRWPASDO" } } }`.

**Comment by wmshek1992** [comment] 2020-04-15 02:52
By following your advise, now the group has 2 owners.

`{"meta":{"id":"87307","topic":"grpqF-Sk_oD-jQ","ts":"2020-04-15T02:26:47.536Z","sub":[{"updated":"2020-04-14T01:40:45.254Z","online":true,"acs":{"mode":"JRWPASDO","given":"JRWPASDO","want":"JRWPASDO"},"read":2,"recv":2,"user":"usrw2g_kxhlL-0"},{"updated":"2020-04-15T02:20:28.896Z","online":true,"acs":{"mode":"JRWPASDO","given":"JRWPASDO","want":"JRWPASDO"},"read":2,"recv":2,"user":"usrE-6UDy41emE"}]}} `


Then I try to give up the ownership from the topic creator. Server gives an error message.

```
{
    "set": {
        "id": "88548",
        "topic": "grpqF-Sk_oD-jQ",
        "sub": {
            "user": "usrw2g_kxhlL-0",
            "mode": "JRWPASD"
        }
    }
}
```
Error
`topic[grpqF-Sk_oD-jQ] meta.Set.Sub failed: cannot unset ownership or self-ban the owner`

**Comment by or-else** [comment] 2020-04-15 05:29
I cannot reproduce. Please show the entire client-side and server-side logs.

**Comment by wmshek1992** [comment] 2020-04-15 07:09
Now the situation is there are 2 owners in the group. The topic creator cannot remove its `O` permission. What I want to do is leaving the topic without involving other users in the group.

## Server received log :
(sid= C3pV-GmSToU is the topic creator, sid=vM3tvDp1WSo is the person I want to transfer the ownership)  

```
2020/04/15 14:43:56 in: '{
    "sub": {
        "id": "103078",
        "topic": "new",
        "set": {
            "desc": {
                "public": {
                    "fn": "test"
                },
                "private": {
                    "comment": "test"
                }
            },
            "tags": [
                "test"
            ]
        },
        "get": {
            "data": {
                "limit": 24
            },
            "what": "data sub desc"
        }
    }
}' ip='[::1]:59642' sid='C3pV-GmSToU' uid='w2g_kxhlL-0'
2020/04/15 14:43:57 in: '{"get":{"id":"102392","topic":"me","what":"sub","sub":{"topic":"grpRG4JhMcITeU"}}}' ip='[::1]:65473' sid='mNBe-wzMwvg' uid='w2g_kxhlL-0'
2020/04/15 14:46:34 in: '{
    "set": {
        "id": "118229",
        "topic": "grpRG4JhMcITeU",
        "sub": {
            "user": "usrE-6UDy41emE",
            "mode":"JRWPASDO"
        }
    }
}' ip='[::1]:59564' sid='C3pV-GmSToU' uid='w2g_kxhlL-0'
2020/04/15 14:46:35 in: '{"get":{"id":"104830","topic":"me","what":"sub","sub":{"topic":"grpRG4JhMcITeU"}}}' ip='[::1]:56229' sid='vM3tvDp1WSo' uid='E-6UDy41emE'
2020/04/15 14:47:06 in: '{"sub":{"id":"104831","topic":"grpRG4JhMcITeU","get":{"data":{"limit":24},"desc":{"ims":"2020-04-15T06:46:34.199Z"},"what":"data sub desc"}}}' ip='[::1]:56229' sid='vM3tvDp1WSo' uid='E-6UDy41emE'
2020/04/15 14:48:37 in: '{
    "set": {
        "id": "88548",
        "topic": "grpIdRMiytKXqI",
        "sub": {
            "user": "usrw2g_kxhlL-0",
            "mode": "JRWPASD"
        }
    }
}' ip='[::1]:59564' sid='C3pV-GmSToU' uid='w2g_kxhlL-0'
2020/04/15 14:48:55 in: '{
    "set": {
        "id": "88548",
        "topic": "grpRG4JhMcITeU",
        "sub": {
            "user": "usrw2g_kxhlL-0",
            "mode": "JRWPASD"
        }
    }
}' ip='[::1]:59564' sid='C3pV-GmSToU' uid='w2g_kxhlL-0'
2020/04/15 14:48:55 topic[grpRG4JhMcITeU] meta.Set.Sub failed: cannot unset ownership or self-ban the owner
2020/04/15 14:49:02 in: '{
    "leave": {
        "id": "118229",
        "topic": "grpIdRMiytKXqI",
        "unsub":true
    }
}' ip='[::1]:59564' sid='C3pV-GmSToU' uid='w2g_kxhlL-0'
2020/04/15 14:49:02 s.leave: must attach first C3pV-GmSToU
2020/04/15 14:49:49 in: '{
    "set": {
        "id": "88548",
        "topic": "grpRG4JhMcITeU",
        "sub": {
            "user": "usrw2g_kxhlL-0",
            "mode": "JRWPAS"
        }
    }
}' ip='[::1]:61691' sid='C3pV-GmSToU' uid='w2g_kxhlL-0'
2020/04/15 14:49:49 topic[grpRG4JhMcITeU] meta.Set.Sub failed: cannot unset ownership or self-ban the owner

```


## Client received log:
```
{"ctrl":{"id":"103078","topic":"grpRG4JhMcITeU","params":{"acs":{"want":"JRWPASDO","given":"JRWPASDO","mode":"JRWPASDO"},"tmpname":"new"},"code":200,"text":"ok","ts":"2020-04-15T06:43:56.851Z"}}
{"meta":{"id":"103078","topic":"grpRG4JhMcITeU","ts":"2020-04-15T06:43:56.859Z","desc":{"updated":"2020-04-15T06:43:56.851Z","touched":"2020-04-15T06:43:56.851Z","online":true,"defacs":{"auth":"JRWPS","anon":"N"},"acs":{"want":"JRWPASDO","given":"JRWPASDO","mode":"JRWPASDO"},"public":{"fn":"test"},"private":{"comment":"test"}}}}
{"meta":{"id":"103078","topic":"grpRG4JhMcITeU","ts":"2020-04-15T06:43:56.859Z","sub":[{"updated":"2020-04-15T06:43:56.858Z","online":true,"acs":{"want":"JRWPASDO","given":"JRWPASDO","mode":"JRWPASDO"},"public":{"fn":"Dave Goliathsson","photo":{"data":"/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAgACADASIAAhEBAxEB/8QAGQAAAwADAAAAAAAAAAAAAAAAAAQFAgMI/8QAIxAAAgIBAwQDAQAAAAAAAAAAAQIAAxEEITEFEhNBYXOxof/EABcBAQEBAQAAAAAAAAAAAAAAAAECAAP/xAAcEQACAwADAQAAAAAAAAAAAAABAgADERIxwUH/2gAMAwEAAhEDEQA/AOqMQ9wkxksu6lfX57URKkICEcktn18CcbH45g3YgSpCT6bbKtSlF9nkDglHIwduQcbShKRwwhCIVbdX1X01frx6LXaPTXv33UVWPjGXQE4kWKzYV+Hwj2Ii5ZdT1GrxN3JSGLMOMnYD9/kozBFWtQqAADgATZGusrpPZmM//9k=","type":"jpeg"}},"private":{"comment":"test"},"user":"usrw2g_kxhlL-0"}]}}
{"ctrl":{"id":"103078","topic":"grpRG4JhMcITeU","params":{"count":0,"what":"data"},"code":200,"text":"ok","ts":"2020-04-15T06:43:56.86Z"}}
{"ctrl":{"id":"118229","topic":"grpRG4JhMcITeU","params":{"acs":{"want":"JRWPASDO","given":"JRWPASDO","mode":"JRWPASDO"},"user":"usrE-6UDy41emE"},"code":200,"text":"ok","ts":"2020-04-15T06:46:34.199Z"}}
{"ctrl":{"id":"88548","topic":"grpRG4JhMcITeU","code":403,"text":"permission denied","ts":"2020-04-15T06:48:55.126Z"}}
{"ctrl":{"id":"88548","topic":"grpRG4JhMcITeU","code":403,"text":"permission denied","ts":"2020-04-15T06:49:49.915Z"}}

```

## log of the user I want to transfer the ownership too.
```

[06:47:06:244] in: {"ctrl":{"id":"104831","topic":"grpRG4JhMcITeU","code":200,"text":"ok","ts":"2020-04-15T06:47:06.239Z"}} 
[06:47:06:248] in: {"meta":{"id":"104831","topic":"grpRG4JhMcITeU","ts":"2020-04-15T06:47:06.239Z","desc":{"created":"2020-04-15T06:43:56.851Z","updated":"2020-04-15T06:43:56.851Z","touched":"2020-04-15T06:43:56.851Z","online":true,"defacs":{"auth":"JRWPS","anon":"N"},"acs":{"mode":"JRWPASDO","given":"JRWPASDO","want":"JRWPASDO"}}}} 
[06:47:06:265] in: {"meta":{"id":"104831","topic":"grpRG4JhMcITeU","ts":"2020-04-15T06:47:06.239Z","sub":[{"updated":"2020-04-15T06:43:56.858Z","online":true,"acs":{"mode":"JRWPASDO","given":"JRWPASDO","want":"JRWPASDO"},"public":{"fn":"Dave Goliathsson","photo":{"data":"<584, bytes: /9j/4AAQSkZJ...srpPZmM//9k=>","type":"jpeg"}},"user":"usrw2g_kxhlL-0"},{"updated":"2020-04-15T06:46:34.199Z","online":true,"acs":{"mode":"JRWPASDO","given":"JRWPASDO","want":"JRWPASDO"},"public":{"fn":"Eve Adams","photo":{"data":"<660, bytes: /9j/4AAQSkZJ...ptuLmm2/u//Z>","type":"jpeg"}},"user":"usrE-6UDy41emE"}]}} 
[06:47:06:278] in: {"ctrl":{"id":"104831","topic":"grpRG4JhMcITeU","params":{"count":0,"what":"data"},"code":200,"text":"ok","ts":"2020-04-15T06:47:06.256Z"}} 
```

**Comment by or-else** [comment] 2020-04-15 07:37
I cannot reproduce

### Server log

```
2020/04/15 10:27:13 in: '{"hi":{"id":"125306","ver":"0.16.5-rc2","ua":"TinodeWeb/0.16.5-rc2 (Chrome/80.0; MacIntel); tinodejs/0.16.5-rc2","lang":"en-US"}}' ip='[::1]:59944' sid='7A4_vbcyrqU' uid=''
2020/04/15 10:27:13 in: '{"login":{"id":"125307","scheme":"basic","secret":"Ym9iOmJvYjEyMw=="}}' ip='[::1]:59944' sid='7A4_vbcyrqU' uid=''
2020/04/15 10:27:13 in: '{"sub":{"id":"125308","topic":"me","get":{"what":"sub desc tags cred"}}}' ip='[::1]:59944' sid='7A4_vbcyrqU' uid='CwJBuZ8FO_4'
2020/04/15 10:27:15 in: '{"sub":{"id":"125309","topic":"grpjxPJWd2mh20","get":{"data":{"limit":24},"desc":{"ims":"2020-04-15T07:14:21.234Z"},"what":"data sub desc"}}}' ip='[::1]:59944' sid='7A4_vbcyrqU' uid='CwJBuZ8FO_4'
2020/04/15 10:27:18 in: '{"set":{"id":"125310","topic":"grpjxPJWd2mh20","sub":{"mode":"JRWPS"}}}' ip='[::1]:59944' sid='7A4_vbcyrqU' uid='CwJBuZ8FO_4'
2020/04/15 10:27:37 in: '{"sub":{"id":"117304","topic":"fnd","get":{"what":"sub"}}}' ip='[::1]:59715' sid='YFr0jm7AafM' uid='wxT7gciHtRY'
2020/04/15 10:27:51 in: '{"leave":{"id":"117306","topic":"grpjxPJWd2mh20"}}' ip='[::1]:59715' sid='YFr0jm7AafM' uid='wxT7gciHtRY'
2020/04/15 10:27:51 in: '{"sub":{"id":"117307","topic":"new117305","set":{"desc":{"public":{"fn":"test"},"private":{"comment":"test"}},"tags":["test"]},"get":{"data":{"limit":24},"what":"data sub desc"}}}' ip='[::1]:59715' sid='YFr0jm7AafM' uid='wxT7gciHtRY'
2020/04/15 10:28:00 in: '{"get":{"id":"117308","topic":"grphZRU_6LcKW8","what":"tags"}}' ip='[::1]:59715' sid='YFr0jm7AafM' uid='wxT7gciHtRY'
2020/04/15 10:28:07 in: '{"set":{"id":"117309","topic":"grphZRU_6LcKW8","sub":{"user":"usrCwJBuZ8FO_4"}}}' ip='[::1]:59715' sid='YFr0jm7AafM' uid='wxT7gciHtRY'
2020/04/15 10:28:08 in: '{"get":{"id":"125311","topic":"me","what":"sub","sub":{"topic":"grphZRU_6LcKW8"}}}' ip='[::1]:59944' sid='7A4_vbcyrqU' uid='CwJBuZ8FO_4'
2020/04/15 10:28:15 in: '{"set":{"id":"117310","topic":"grphZRU_6LcKW8","sub":{"user":"usrCwJBuZ8FO_4","mode":"JRWPSO"}}}' ip='[::1]:59715' sid='YFr0jm7AafM' uid='wxT7gciHtRY'
2020/04/15 10:28:30 in: '{"leave":{"id":"125312","topic":"grpjxPJWd2mh20"}}' ip='[::1]:59944' sid='7A4_vbcyrqU' uid='CwJBuZ8FO_4'
2020/04/15 10:28:30 in: '{"sub":{"id":"125313","topic":"grphZRU_6LcKW8","get":{"data":{"limit":24},"desc":{"ims":"2020-04-15T07:28:07.652Z"},"what":"data sub desc"}}}' ip='[::1]:59944' sid='7A4_vbcyrqU' uid='CwJBuZ8FO_4'
2020/04/15 10:28:39 in: '{"set":{"id":"125314","topic":"grphZRU_6LcKW8","sub":{"mode":"JRWPSO"}}}' ip='[::1]:59944' sid='7A4_vbcyrqU' uid='CwJBuZ8FO_4'
2020/04/15 10:28:39 in: '{"get":{"id":"125315","topic":"grphZRU_6LcKW8","what":"tags"}}' ip='[::1]:59944' sid='7A4_vbcyrqU' uid='CwJBuZ8FO_4'
2020/04/15 10:28:39 in: '{"get":{"id":"125316","topic":"grphZRU_6LcKW8","what":"tags"}}' ip='[::1]:59944' sid='7A4_vbcyrqU' uid='CwJBuZ8FO_4'
2020/04/15 10:29:01 in: '{"leave":{"id":"117311","topic":"grphZRU_6LcKW8","unsub":true}}' ip='[::1]:59715' sid='YFr0jm7AafM' uid='wxT7gciHtRY'
```

### User Alice (first owner) log

```
[07:27:37.702] out: {"sub":{"id":"117304","topic":"fnd","get":{"what":"sub"}}} 
[07:27:37.741] in: {"ctrl":{"id":"117304","topic":"fnd","code":200,"text":"ok","ts":"2020-04-15T07:27:37.716Z"}} 
[07:27:37.745] in: {"ctrl":{"id":"117304","topic":"fnd","params":{"what":"sub"},"code":200,"text":"ok","ts":"2020-04-15T07:27:37.716Z"}} 
[07:27:51.567] out: {"leave":{"id":"117306","topic":"grpjxPJWd2mh20"}} 
[07:27:51.569] out: {"sub":{"id":"117307","topic":"new117305","set":{"desc":{"public":{"fn":"test"},"private":{"comment":"test"}},"tags":["test"]},"get":{"data":{"limit":24},"what":"data sub desc"}}} 
[07:27:51.602] in: {"ctrl":{"id":"117306","topic":"grpjxPJWd2mh20","code":200,"text":"ok","ts":"2020-04-15T07:27:51.569Z"}} 
[07:27:51.628] in: {"ctrl":{"id":"117307","topic":"grphZRU_6LcKW8","params":{"acs":{"mode":"JRWPASDO","given":"JRWPASDO","want":"JRWPASDO"},"tmpname":"new117305"},"code":200,"text":"ok","ts":"2020-04-15T07:27:51.570Z"}} 
[07:27:51.663] in: {"meta":{"id":"117307","topic":"grphZRU_6LcKW8","ts":"2020-04-15T07:27:51.627Z","desc":{"updated":"2020-04-15T07:27:51.57Z","touched":"2020-04-15T07:27:51.57Z","online":true,"defacs":{"auth":"JRWPS","anon":"N"},"acs":{"mode":"JRWPASDO","given":"JRWPASDO","want":"JRWPASDO"},"public":{"fn":"test"},"private":{"comment":"test"}}}} 
[07:27:51.664] in: {"pres":{"topic":"me","src":"grphZRU_6LcKW8","what":"on"}} 
[07:27:51.665] in: {"meta":{"id":"117307","topic":"grphZRU_6LcKW8","ts":"2020-04-15T07:27:51.627Z","sub":[{"updated":"2020-04-15T07:27:51.61Z","online":true,"acs":{"mode":"JRWPASDO","given":"JRWPASDO","want":"JRWPASDO"},"public":{"fn":"Alice Johnson","photo":{"data":"<8908, bytes: /9j/4AAQSkZJ...sUaqGs//2Q==>","type":"jpg"}},"private":{"comment":"test"},"user":"usrwxT7gciHtRY"}]}} 
[07:27:51.665] in: {"ctrl":{"id":"117307","topic":"grphZRU_6LcKW8","params":{"count":0,"what":"data"},"code":200,"text":"ok","ts":"2020-04-15T07:27:51.631Z"}} 
[07:28:00.517] out: {"get":{"id":"117308","topic":"grphZRU_6LcKW8","what":"tags"}} 
[07:28:00.545] in: {"meta":{"id":"117308","topic":"grphZRU_6LcKW8","ts":"2020-04-15T07:28:00.518Z","tags":["test"]}} 
[07:28:07.649] out: {"set":{"id":"117309","topic":"grphZRU_6LcKW8","sub":{"user":"usrCwJBuZ8FO_4"}}} 
[07:28:07.667] in: {"ctrl":{"id":"117309","topic":"grphZRU_6LcKW8","params":{"acs":{"mode":"JRWPS","given":"JRWPS","want":"JRWPS"},"user":"usrCwJBuZ8FO_4"},"code":200,"text":"ok","ts":"2020-04-15T07:28:07.650Z"}} 
[07:28:15.962] out: {"set":{"id":"117310","topic":"grphZRU_6LcKW8","sub":{"user":"usrCwJBuZ8FO_4","mode":"JRWPSO"}}} 
tinode.js:1196 
[07:28:16.002] in: {"ctrl":{"id":"117310","topic":"grphZRU_6LcKW8","params":{"acs":{"mode":"JRWPS","given":"JRWPSO","want":"JRWPS"},"user":"usrCwJBuZ8FO_4"},"code":200,"text":"ok","ts":"2020-04-15T07:28:15.986Z"}} 
[07:28:30.753] in: {"pres":{"topic":"grphZRU_6LcKW8","src":"usrCwJBuZ8FO_4","what":"on"}} 
[07:28:35.749] in: {"pres":{"topic":"me","src":"grpjxPJWd2mh20","what":"off"}} 
[07:28:39.795] in: {"pres":{"topic":"grphZRU_6LcKW8","src":"usrCwJBuZ8FO_4","what":"acs","dacs":{"want":"+O"}}} 
[07:29:01.270] out: {"leave":{"id":"117311","topic":"grphZRU_6LcKW8","unsub":true}} 
[07:29:01.289] in: {"ctrl":{"id":"117311","topic":"grphZRU_6LcKW8","code":200,"text":"ok","ts":"2020-04-15T07:29:01.271Z"}} 
```

### User Bob (second owner) log

```
[07:28:08.976] out: {"get":{"id":"125311","topic":"me","what":"sub","sub":{"topic":"grphZRU_6LcKW8"}}} 
[07:28:08.992] in: {"meta":{"id":"125311","topic":"me","ts":"2020-04-15T07:28:08.977Z","sub":[{"updated":"2020-04-15T07:28:07.652Z","online":true,"acs":{"mode":"JRWPS","given":"JRWPS","want":"JRWPS"},"public":{"fn":"test"},"topic":"grphZRU_6LcKW8","touched":"2020-04-15T07:28:07.652Z"}]}} 
[07:28:16.002] in: {"pres":{"topic":"me","src":"grphZRU_6LcKW8","what":"acs","act":"usrwxT7gciHtRY","dacs":{"given":"+O"}}} 
[07:28:30.744] out: {"leave":{"id":"125312","topic":"grpjxPJWd2mh20"}} 
[07:28:30.745] out: {"sub":{"id":"125313","topic":"grphZRU_6LcKW8","get":{"data":{"limit":24},"desc":{"ims":"2020-04-15T07:28:07.652Z"},"what":"data sub desc"}}} 
[07:28:30.755] in: {"ctrl":{"id":"125312","topic":"grpjxPJWd2mh20","code":200,"text":"ok","ts":"2020-04-15T07:28:30.746Z"}} 
[07:28:30.757] in: {"ctrl":{"id":"125313","topic":"grphZRU_6LcKW8","code":200,"text":"ok","ts":"2020-04-15T07:28:30.746Z"}} 
[07:28:30.765] in: {"meta":{"id":"125313","topic":"grphZRU_6LcKW8","ts":"2020-04-15T07:28:30.746Z","desc":{"created":"2020-04-15T07:27:51.57Z","updated":"2020-04-15T07:27:51.57Z","touched":"2020-04-15T07:27:51.57Z","online":true,"defacs":{"auth":"JRWPS","anon":"N"},"acs":{"mode":"JRWPS","given":"JRWPSO","want":"JRWPS"}}}} 
[07:28:30.766] in: {"meta":{"id":"125313","topic":"grphZRU_6LcKW8","ts":"2020-04-15T07:28:30.747Z","sub":[{"updated":"2020-04-15T07:28:07.652Z","online":true,"acs":{"mode":"JRWPS","given":"JRWPSO","want":"JRWPS"},"public":{"fn":"Bob Smith","photo":{"data":"<7236, bytes: /9j/4AAQSkZJ...30e375//2Q==>","type":"jpg"}},"user":"usrCwJBuZ8FO_4"},{"updated":"2020-04-15T07:27:51.61Z","online":true,"acs":{"mode":"JRWPASDO","given":"JRWPASDO","want":"JRWPASDO"},"public":{"fn":"Alice Johnson","photo":{"data":"<8908, bytes: /9j/4AAQSkZJ...sUaqGs//2Q==>","type":"jpg"}},"user":"usrwxT7gciHtRY"}]}} 
[07:28:30.767] in: {"ctrl":{"id":"125313","topic":"grphZRU_6LcKW8","params":{"count":0,"what":"data"},"code":200,"text":"ok","ts":"2020-04-15T07:28:30.750Z"}} 
[07:28:35.749] in: {"pres":{"topic":"me","src":"grpjxPJWd2mh20","what":"off"}} 
[07:28:39.751] out: {"set":{"id":"125314","topic":"grphZRU_6LcKW8","sub":{"mode":"JRWPSO"}}} 
[07:28:39.795] in: {"ctrl":{"id":"125314","topic":"grphZRU_6LcKW8","params":{"acs":{"mode":"JRWPSO","given":"JRWPSO","want":"JRWPSO"}},"code":200,"text":"ok","ts":"2020-04-15T07:28:39.752Z"}} 
[07:28:39.814] out: {"get":{"id":"125315","topic":"grphZRU_6LcKW8","what":"tags"}} 
[07:28:39.836] out: {"get":{"id":"125316","topic":"grphZRU_6LcKW8","what":"tags"}} 
[07:28:39.852] in: {"meta":{"id":"125315","topic":"grphZRU_6LcKW8","ts":"2020-04-15T07:28:39.815Z","tags":["test"]}} 
[07:28:39.853] in: {"meta":{"id":"125316","topic":"grphZRU_6LcKW8","ts":"2020-04-15T07:28:39.837Z","tags":["test"]}} 
[07:29:01.290] in: {"pres":{"topic":"grphZRU_6LcKW8","src":"usrwxT7gciHtRY","what":"acs","dacs":{"want":"N","given":"N"}}} 
[07:29:01.290] in: {"pres":{"topic":"grphZRU_6LcKW8","src":"usrwxT7gciHtRY","what":"off"}} 
```

**Closed** 2020-07-07 19:19 UTC
Labels: cannot reproduce, question
