### ISSUE TITLE
Always online users

### ISSUE THREAD

**Issue by acidlynx** [tinode/chat#454] opened 2020-05-12 04:09 UTC
### Subject of the issue
Hello!

I have several users that online all the time. If I subscribe to topic "me" to them, I get "{pres {topic=me what=on}" every time I start session of my user.
All that users are really offline (we have only one point of access - our mobile app). But I get report about their wrong online status.

### Is this a bug report of a feature request?
- [x] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * Linux
  * https://chat-web.staging.streamlayer.io
  * RethinkDB

#### Client-side
- [x] TinodeWeb/tinodejs: javascript client
  * https://chat-web.staging.streamlayer.io
- [x] our version of mobile apps, that uses api via gRPC
- [ ] Tindroid: Android app
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
- [ ] tn-cli
  * Python version
- [ ] Chatbot
  * Python version
- Version of the client, e.g. `0.16`

### Steps to reproduce
Please, ask me for credentials to web interface and RethinkDB. If we log in to webChat we get wrong online status for 2 users.

### Expected behaviour
Get correct online status (online and offline)

### Actual behaviour
Users are always online

### Server-side log
Copy server-side log here. You may also attach it to the issue as a file.

### Client-side log
Copy client-side log here (Android logcat, Javascript console, etc). You may also attach it to the issue as a file.
Client side log is here.
[tinode-client.log](https://github.com/tinode/chat/files/4613329/tinode-client.log)

**Comment by or-else** [comment] 2020-05-12 06:20
Is this a cluster or a stand-alone server?

What kind of client software did these clients use to connect to the server? How do you know they are not connected anymore?

**Comment by acidlynx** [comment] 2020-05-12 07:25
This is stand-alone version.

We are develop our own mobile SDK and use gRPC to connect to tinode API.
They are not connected because they close all apps, debug sessions, etc.

Another question. How tinode understand, user is online or offline?

**Comment by acidlynx** [comment] 2020-05-12 07:54
@or-else We updated server up to v0.16.5 and bug was fixed.

**Comment by acidlynx** [comment] 2020-05-22 18:29
Hello! It seems update simply flush any sessions counter. Because we have the same bug now.

**Comment by or-else** [comment] 2020-05-23 04:47
If this is a bug in Tinode code, please file a bug report listing steps to reproduce. For instance, use `tn-cli` as a client.

If this is a bug in your code then you need to debug it yourself.

**Comment by acidlynx** [comment] 2020-06-12 03:21
@or-else Try this flow please.

We use your API with our own implementation (iOS, Android).
Connection via gRPC.
API version 0.16.5
DB RethinkDB

So if we
1. Log in to chat with device1
2. Then log in to chat with device2 (device1 is still online)
3. Then log in to chat with device3 (device1 and device2 is still online)
4. Then close gRPC connection on device2 or device3.

In this case we get that tinode isn't remove data about sessions from the DB and show that this user is always online.

Open-close gRPC connections are not take effect and tinode is not remove inactive (no connection) sessions.


Also I want to try do this with your API implementation and your apps.

**Comment by or-else** [comment] 2020-06-12 03:56
Should it be the same user or three different users?

**Comment by acidlynx** [comment] 2020-06-12 03:57
The same user.

**Comment by or-else** [comment] 2020-06-12 04:47
Then I don't understand. You connect 3 times, disconnect once, i.e. two connections are still live. What do you expect to see?

**Comment by acidlynx** [comment] 2020-06-12 05:01
Oh. Sorry. I lost the 5th step.
5. After the first disconnection. Send messages from other connections. And then disconnect all devices.
6. When all devices disconnected, other account can see that the first user is online (api sends `presence` about).

**Comment by acidlynx** [comment] 2020-06-12 05:03
As I understand somewhere incorrect work of session's disconnection handler. Or even sessions counter.

**Comment by or-else** [comment] 2020-06-12 06:59
I cannot reproduce. Please either provide steps to reproduce using stock tools, or close this ticket. If you decide to provide steps to reproduce, please do so in the same format as below. Thanks. 


Session 1 (bob):
```
$ python3 tn-cli.py --login-basic bob:bob123
Tinode command line client. Version 1.5.0/0.16.6b4; gRPC/1.19.0.
Server at 'localhost:16060' 
Logging in with login:password bob:bob123
<= Connected to server: maxFileUploadSize: 8388608; maxTagCount: 16; ver: 0.16; maxMessageSize: 262144; maxSubscriberCount: 32; build: rethinkdb:undef 
<= 201 created 
<= Authenticated as usrZ_AHakJIxeo 
<= 200 ok 
tn> sub me
<= 200 ok (me) 
tn> .exit 
Shutting down...
```

Session 2 (bob):
```
$ python3 tn-cli.py --login-basic bob:bob123
Tinode command line client. Version 1.5.0/0.16.6b4; gRPC/1.19.0.
Server at 'localhost:16060' 
Logging in with login:password bob:bob123
<= Connected to server: ver: 0.16; maxMessageSize: 262144; maxSubscriberCount: 32; build: rethinkdb:undef; maxFileUploadSize: 8388608; maxTagCount: 16 
<= 201 created 
<= Authenticated as usrZ_AHakJIxeo 
<= 200 ok 
tn> sub me 
<= 200 ok (me) 
tn> sub usrALibpNNFFy4 
<= 200 ok (usrALibpNNFFy4) 
tn> pub usrALibpNNFFy4 "hi 1" 
<= 202 accepted (usrALibpNNFFy4) 
<=  
From: usrZ_AHakJIxeo 
<= Topic: usrALibpNNFFy4 
<= Seq: 26 
<= hi 2 
tn> exit  
Shutting down...
```

Session 3 (bob):
```
$ python3 tn-cli.py --login-basic bob:bob123
Tinode command line client. Version 1.5.0/0.16.6b4; gRPC/1.19.0.
Server at 'localhost:16060' 
Logging in with login:password bob:bob123
<= Connected to server: ver: 0.16; maxMessageSize: 262144; maxSubscriberCount: 32; build: rethinkdb:undef; maxFileUploadSize: 8388608; maxTagCount: 16 
<= 201 created 
<= Authenticated as usrZ_AHakJIxeo 
<= 200 ok 
tn> sub me 
<= 200 ok (me) 
tn> sub usrALibpNNFFy4 
<= 200 ok (usrALibpNNFFy4) 
<=  
From: usrZ_AHakJIxeo 
<= Topic: usrALibpNNFFy4 
<= Seq: 25 
<= hi 1 
tn> pub usrALibpNNFFy4 "hi 2"
<= 202 accepted (usrALibpNNFFy4) 
tn> exit 
Shutting down...
```

Webapp (alice)
```
[06:44:44.642] in: {"pres":{"topic":"me","src":"usrZ_AHakJIxeo","what":"on","ua":"tn-cli/1.5.0 (Darwin/19.4.0); gRPC-python/0.16.6b4+1.19.0"}} 
tinode.js:1198 [06:47:04.135] in: {"pres":{"topic":"me","src":"usrZ_AHakJIxeo","what":"msg","seq":25,"act":"usrZ_AHakJIxeo"}} 
tinode.js:1198 [06:47:20.045] in: {"pres":{"topic":"me","src":"usrZ_AHakJIxeo","what":"msg","seq":26,"act":"usrZ_AHakJIxeo"}} 
tinode.js:1198 [06:47:40.052] in: {"pres":{"topic":"me","src":"usrZ_AHakJIxeo","what":"off","ua":"tn-cli/1.5.0 (Darwin/19.4.0); gRPC-python/0.16.6b4+1.19.0"}} 
```

**Comment by acidlynx** [comment] 2020-06-16 03:37
I'll try to reproduce with tn-cli.

**Comment by or-else** [comment] 2020-07-07 19:20
Any update on this?

**Closed** 2020-07-19 03:21 UTC
Labels: cannot reproduce
