### ISSUE TITLE
v0.16.8 non-idempotent meta

### ISSUE THREAD

**Issue by afoninsky** [tinode/chat#562] opened 2020-11-01 14:42 UTC
### Subject of the issue
v0.16.8-rc2 returns channel name in different formats

### Your environment
Able to repeat:
_Client: TinodeWeb/0.16.8 (tinodejs/0.16.8-beta1)
Server: 0.16 mongodb:v0.16.8 (messenger-staging.fdvr.co)
Server: 0.16 mongodb:v0.16.8-rc2 (messenger-staging.fdvr.co)_

Bug does not exist:
_Client: TinodeWeb/0.16.7 (tinodejs/0.16.7-rc2)
Server: 0.16 mongodb:v0.16.7 (messenger-staging.fdvr.co)_

### Steps to reproduce
1. Create a topic with "user1"
```
in: {"meta":{"id":"69803","topic":"new69802","ts":"2020-11-01T14:17:31.262Z","desc":{"updated":"2020-11-01T14:17:31.259Z","touched":"2020-11-01T14:17:31.259Z","online":true,"defacs":{"auth":"JRWPS","anon":"N"},"acs":{"mode":"JRWPASDO","given":"JRWPASDO","want":"JRWPASDO"},"public":{"fn":"test"}}}} 
```
2. Find topic with "user2" using its id:
```
in: {"meta":{"id":"101944","topic":"grp5KzJ3NQGngU","ts":"2020-11-01T14:20:58.199Z","desc":{"updated":"2020-11-01T14:17:31.259Z","touched":"2020-11-01T14:17:31.259Z","online":true,"defacs":{"auth":"JRWPS","anon":"N"},"acs":{"mode":"JRWPS","given":"JRWPS","want":"JRWPS"},"public":[{"Key":"fn","Value":"test"}]}}} 
```

### Expected behaviour
`.public` field should contain an object in both cases

### Actual behaviour
`.public` field contains an array in case of subscription:
- js sdk (web ui) displays "Unknown" channel name
- android sdk crashes as another format expected

<img width="982" alt="create" src="https://user-images.githubusercontent.com/15193941/97805834-bc7de880-1c58-11eb-9259-77f553b77a49.png">

**Comment by or-else** [comment] 2020-11-01 22:18
Yes, I can reproduce.

**Comment by or-else** [comment] 2020-11-01 23:44
Fixed in https://github.com/tinode/chat/commit/8c73bb5bd63ed17fbc0ca40ad4498d11b9f82342.
It looks like this bug is not new. It's been like that for a while. Just no one caught it.

**Comment by afoninsky** [comment] 2020-11-02 08:08
Thank you for the fast fix. One more question:
Do you have "nightly" docker builds or plan to have? It can be convenient for early adopters.
I can create an issue if it is needed.

**Comment by or-else** [comment] 2020-11-02 14:29
We don't. Docker builds are not fully automated. They take about 20 min. It would be highly appreciated if you could help with setting up an automatic build pipeline.

**Comment by or-else** [comment] 2020-12-10 22:53
Released

**Closed by or-else** 2020-12-10 22:53 UTC
Labels: bug
