### ISSUE TITLE
Features requests [ ] Feature request

### ISSUE THREAD

**Issue by sanmiguel2019** [tinode/chat#443] opened 2020-05-05 16:52 UTC
Features request:

1. Possibility to send voice messages
2. User's "last seen" time
3. Possitility to delete unread messages choosing "delete for me" or "delete for me and recipient"
4. Possilility to delete "Content deleted" mark which stacks forever in the conversation after deleting a message.
4. Possibility to see the time when message has been read by recipient. When selecting a message there is "i" icon on the top but it does not work and I don't understand it's purpose.
5. Emojis and maybe stickers
Emojis: [https://www.androidhive.info/2016/11/android-integrate-emojis-keyboard-app/](url)
6. Possibility to resend messages.
7. One to one conversations list and groups conversations list should be separated. We always read private messages but messages received from groups we read when we have a free time. A cocktail of group and private conversations can cause users to miss important messages.
8. Possibility to record and send videos.
9. Please put a part of last message below each user name in the conversations list. The list looks empty because contains nothing more than usernames and avatars.
10. Link previews

**Comment by or-else** [comment] 2020-05-05 18:11
1. That has to wait until someone contributes it.
2. Will add in the next version.
3. "Delete for me" is available now. "Delete for the recipient" has to wait for the message editing feature.
4. I'm not sure it's a good idea. why is it important?
5. It's not obvious to me that this is a needed feature. It has implication for privacy.
6. That has to wait until someone contributes it.
7. Please explain.
8. FB Messenger, Whatsapp and Telegram don't do it. Which messaging app do you use?
9. Same as 1 and 6.

**Comment by sanmiguel2019** [comment] 2020-05-05 21:47
4. That's a thing what I hate in Whatsapp. If I decided to delete a message, I want to delete it completly. In Whatsapp apears "message deleted" and I have to tap one more time to delete this mark that I don't need at all. In Tinode it's not even possible to delete it. Who needs a conversation full of marks "Content deleted?". It's the same as not to delete message. But of course it's your project.

7. For example, in Whatsapp I receive a message and when I tap on it, appears option to resend received message to other contacts. In Tinode it's not possible.

8. Yes, they don't do it and I don't know why. If you are a member of, lets say, 20 groups, all groups will be always on the top of the conversations list and you will search your contacts among all these groups. It's is very annoying.

I added two more points 10 and 11 to the features request.

Regards.

**Comment by or-else** [comment] 2020-05-06 07:27
4. OK, I'll think about it more.
5. There is some confusion here. 5 was "Possibility to see the time when message has been read by recipient." I think you meant 7 in your comment. Why is 5 needed? WhatsApp has it, Telegram & FB Messenger do not. I don't want Tinode to be a collection of unnecessary or rarely used features.
7. Replies and forwards. Yes, that's something that we want to do.
6. I think there is some confusion here. Your comment seems to be about 8.
8. Telegram actually has a feature https://telegram.org/blog/folders which is kind of strange because the first folder still has all the chats anyway. Let me think about it some more.
10. Yes, that's can be added now. It used to be hard to do, now it's OK.
11. The same as 1, 6, 9.

**Comment by or-else** [comment] 2021-06-24 04:08
Let's close this issue because it's very hard to track. I've created separate issues as well as linked requests to existing issues:

1. Dupe of #237.
2. Done
3. Dupe of #249, #569.
4. Created issue: #670.  
5. Created issue: #671.
6. Emoji and stickers
  a. FR: emoji dupe of tinode/webapp/issues/30
  b. FR: stickers created separate issue: #672
7. Purpose unclear
8. Created issue: #669
9. Dupe of #237
10. Done
11. Dupe of #254

**Closed by or-else** 2021-06-24 04:08 UTC
Labels: feature request

**Comment by Runningwolf2869** [comment] 2021-07-23 07:23
@natashahammond
