### ISSUE TITLE
too many goruntines cause very high memory usage.

### ISSUE THREAD

**Issue by hhy5861** [tinode/chat#529] opened 2020-08-27 05:14 UTC
```
goroutine profile: total 920756
626254 @ 0x437070 0x447363 0xb3570f 0x4671c1
#	0xb3570e	main.(*Session).clusterWriteLoop+0x14e	/Users/mike/golang/poizon/duinfr/spider/server/cluster.go:1013

278952 @ 0x437070 0x447363 0xb77212 0xb65cdb 0x4671c1
#	0xb77211	main.(*Topic).runProxy+0x251	/Users/mike/golang/poizon/duinfr/spider/server/topic_proxy.go:22
#	0xb65cda	main.(*Topic).run+0x3a		/Users/mike/golang/poizon/duinfr/spider/server/topic.go:169

9478 @ 0x437070 0x447363 0xb664cd 0xb65cf8 0x4671c1
#	0xb664cc	main.(*Topic).runLocal+0x2bc	/Users/mike/golang/poizon/duinfr/spider/server/topic.go:219
#	0xb65cf7	main.(*Topic).run+0x57		/Users/mike/golang/poizon/duinfr/spider/server/topic.go:167

3289 @ 0x437070 0x447363 0xb3b952 0x4671c1
#	0xb3b951	main.(*Session).writeLoop+0x1c1	/Users/mike/golang/poizon/duinfr/spider/server/hdl_websock.go:76

2678 @ 0x437070 0x43002a 0x42f595 0x4dcfe5 0x4dde7b 0x4dde5d 0x56d7bf 0x57ff3e 0x6500d0 0x47ee31 0x65031c 0x64e8d5 0x6529fb 0x652a06 0x4fe443 0x4fe5af 0x8d2d30 0x8d528c 0x8d631f 0x8d6a9f 0xb3b5ec 0x4671c1
#	0x42f594	internal/poll.runtime_pollWait+0x54			/Users/mike/.gvm/gos/go1.14.6/src/runtime/netpoll.go:203
#	0x4dcfe4	internal/poll.(*pollDesc).wait+0x44			/Users/mike/.gvm/gos/go1.14.6/src/internal/poll/fd_poll_runtime.go:87
#	0x4dde7a	internal/poll.(*pollDesc).waitRead+0x19a		/Users/mike/.gvm/gos/go1.14.6/src/internal/poll/fd_poll_runtime.go:92
#	0x4dde5c	internal/poll.(*FD).Read+0x17c				/Users/mike/.gvm/gos/go1.14.6/src/internal/poll/fd_unix.go:169
#	0x56d7be	net.(*netFD).Read+0x4e					/Users/mike/.gvm/gos/go1.14.6/src/net/fd_unix.go:202
#	0x57ff3d	net.(*conn).Read+0x8d					/Users/mike/.gvm/gos/go1.14.6/src/net/net.go:184
#	0x6500cf	crypto/tls.(*atLeastReader).Read+0x5f			/Users/mike/.gvm/gos/go1.14.6/src/crypto/tls/conn.go:760
#	0x47ee30	bytes.(*Buffer).ReadFrom+0xb0				/Users/mike/.gvm/gos/go1.14.6/src/bytes/buffer.go:204
#	0x65031b	crypto/tls.(*Conn).readFromUntil+0xeb			/Users/mike/.gvm/gos/go1.14.6/src/crypto/tls/conn.go:782
#	0x64e8d4	crypto/tls.(*Conn).readRecordOrCCS+0x114		/Users/mike/.gvm/gos/go1.14.6/src/crypto/tls/conn.go:589
#	0x6529fa	crypto/tls.(*Conn).readRecord+0x15a			/Users/mike/.gvm/gos/go1.14.6/src/crypto/tls/conn.go:557
#	0x652a05	crypto/tls.(*Conn).Read+0x165				/Users/mike/.gvm/gos/go1.14.6/src/crypto/tls/conn.go:1233
#	0x4fe442	bufio.(*Reader).fill+0x102				/Users/mike/.gvm/gos/go1.14.6/src/bufio/bufio.go:100
#	0x4fe5ae	bufio.(*Reader).Peek+0x4e				/Users/mike/.gvm/gos/go1.14.6/src/bufio/bufio.go:138
#	0x8d2d2f	github.com/gorilla/websocket.(*Conn).read+0x3f		/Users/mike/.gvm/pkgsets/go1.14.6/global/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:370
#	0x8d528b	github.com/gorilla/websocket.(*Conn).advanceFrame+0x5b	/Users/mike/.gvm/pkgsets/go1.14.6/global/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:798
#	0x8d631e	github.com/gorilla/websocket.(*Conn).NextReader+0x8e	/Users/mike/.gvm/pkgsets/go1.14.6/global/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:980
#	0x8d6a9e	github.com/gorilla/websocket.(*Conn).ReadMessage+0x2e	/Users/mike/.gvm/pkgsets/go1.14.6/global/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:1064
#	0xb3b5eb	main.(*Session).readLoop+0x14b				/Users/mike/golang/poizon/duinfr/spider/server/hdl_websock.go:54

19 @ 0x437070 0x43002a 0x42f595 0x4dcfe5 0x4dde7b 0x4dde5d 0x56d7bf 0x57ff3e 0x4feaff 0x4754d7 0x506b8f 0x506b42 0x5111e7 0x51173c 0x511a4b 0x5118cd 0x781495 0x780765 0x4671c1
#	0x42f594	internal/poll.runtime_pollWait+0x54			/Users/mike/.gvm/gos/go1.14.6/src/runtime/netpoll.go:203
#	0x4dcfe4	internal/poll.(*pollDesc).wait+0x44			/Users/mike/.gvm/gos/go1.14.6/src/internal/poll/fd_poll_runtime.go:87
#	0x4dde7a	internal/poll.(*pollDesc).waitRead+0x19a		/Users/mike/.gvm/gos/go1.14.6/src/internal/poll/fd_poll_runtime.go:92
#	0x4dde5c	internal/poll.(*FD).Read+0x17c				/Users/mike/.gvm/gos/go1.14.6/src/internal/poll/fd_unix.go:169
#	0x56d7be	net.(*netFD).Read+0x4e					/Users/mike/.gvm/gos/go1.14.6/src/net/fd_unix.go:202
#	0x57ff3d	net.(*conn).Read+0x8d					/Users/mike/.gvm/gos/go1.14.6/src/net/net.go:184
#	0x4feafe	bufio.(*Reader).Read+0x24e				/Users/mike/.gvm/gos/go1.14.6/src/bufio/bufio.go:226
#	0x4754d6	io.ReadAtLeast+0x86					/Users/mike/.gvm/gos/go1.14.6/src/io/io.go:310
#	0x506b8e	io.ReadFull+0x6e					/Users/mike/.gvm/gos/go1.14.6/src/io/io.go:329
#	0x506b41	encoding/gob.decodeUintReader+0x21			/Users/mike/.gvm/gos/go1.14.6/src/encoding/gob/decode.go:120
#	0x5111e6	encoding/gob.(*Decoder).recvMessage+0x56		/Users/mike/.gvm/gos/go1.14.6/src/encoding/gob/decoder.go:81
#	0x51173b	encoding/gob.(*Decoder).decodeTypeSequence+0x10b	/Users/mike/.gvm/gos/go1.14.6/src/encoding/gob/decoder.go:143
#	0x511a4a	encoding/gob.(*Decoder).DecodeValue+0xda		/Users/mike/.gvm/gos/go1.14.6/src/encoding/gob/decoder.go:211
#	0x5118cc	encoding/gob.(*Decoder).Decode+0x16c			/Users/mike/.gvm/gos/go1.14.6/src/encoding/gob/decoder.go:188
#	0x781494	net/rpc.(*gobClientCodec).ReadResponseHeader+0x44	/Users/mike/.gvm/gos/go1.14.6/src/net/rpc/client.go:228
#	0x780764	net/rpc.(*Client).input+0xa4				/Users/mike/.gvm/gos/go1.14.6/src/net/rpc/client.go:109

19 @ 0x437070 0x43002a 0x42f595 0x4dcfe5 0x4dde7b 0x4dde5d 0x56d7bf 0x57ff3e 0x4feaff 0x4754d7 0x506b8f 0x506b42 0x5111e7 0x51173c 0x511a4b 0x5118cd 0x783aa5 0x7852c7 0x784bca 0x784167 0x783fb9 0x4671c1
#	0x42f594	internal/poll.runtime_pollWait+0x54			/Users/mike/.gvm/gos/go1.14.6/src/runtime/netpoll.go:203
#	0x4dcfe4	internal/poll.(*pollDesc).wait+0x44			/Users/mike/.gvm/gos/go1.14.6/src/internal/poll/fd_poll_runtime.go:87
#	0x4dde7a	internal/poll.(*pollDesc).waitRead+0x19a		/Users/mike/.gvm/gos/go1.14.6/src/internal/poll/fd_poll_runtime.go:92
#	0x4dde5c	internal/poll.(*FD).Read+0x17c				/Users/mike/.gvm/gos/go1.14.6/src/internal/poll/fd_unix.go:169
#	0x56d7be	net.(*netFD).Read+0x4e					/Users/mike/.gvm/gos/go1.14.6/src/net/fd_unix.go:202
#	0x57ff3d	net.(*conn).Read+0x8d					/Users/mike/.gvm/gos/go1.14.6/src/net/net.go:184
#	0x4feafe	bufio.(*Reader).Read+0x24e				/Users/mike/.gvm/gos/go1.14.6/src/bufio/bufio.go:226
#	0x4754d6	io.ReadAtLeast+0x86					/Users/mike/.gvm/gos/go1.14.6/src/io/io.go:310
#	0x506b8e	io.ReadFull+0x6e					/Users/mike/.gvm/gos/go1.14.6/src/io/io.go:329
#	0x506b41	encoding/gob.decodeUintReader+0x21			/Users/mike/.gvm/gos/go1.14.6/src/encoding/gob/decode.go:120
#	0x5111e6	encoding/gob.(*Decoder).recvMessage+0x56		/Users/mike/.gvm/gos/go1.14.6/src/encoding/gob/decoder.go:81
#	0x51173b	encoding/gob.(*Decoder).decodeTypeSequence+0x10b	/Users/mike/.gvm/gos/go1.14.6/src/encoding/gob/decoder.go:143
#	0x511a4a	encoding/gob.(*Decoder).DecodeValue+0xda		/Users/mike/.gvm/gos/go1.14.6/src/encoding/gob/decoder.go:211
#	0x5118cc	encoding/gob.(*Decoder).Decode+0x16c			/Users/mike/.gvm/gos/go1.14.6/src/encoding/gob/decoder.go:188
#	0x783aa4	net/rpc.(*gobServerCodec).ReadRequestHeader+0x44	/Users/mike/.gvm/gos/go1.14.6/src/net/rpc/server.go:397
#	0x7852c6	net/rpc.(*Server).readRequestHeader+0x66		/Users/mike/.gvm/gos/go1.14.6/src/net/rpc/server.go:583
#	0x784bc9	net/rpc.(*Server).readRequest+0x59			/Users/mike/.gvm/gos/go1.14.6/src/net/rpc/server.go:543
#	0x784166	net/rpc.(*Server).ServeCodec+0x96			/Users/mike/.gvm/gos/go1.14.6/src/net/rpc/server.go:458
#	0x783fb8	net/rpc.(*Server).ServeConn+0x158			/Users/mike/.gvm/gos/go1.14.6/src/net/rpc/server.go:449

15 @ 0x437070 0x43002a 0x42f595 0x4dcfe5 0x4dde7b 0x4dde5d 0x56d7bf 0x57ff3e 0x6500d0 0x47ee31 0x65031c 0x64e8d5 0x6511fd 0x651208 0x66a4da 0x6684af 0x668061 0x653151 0x70ec5d 0x4671c1
#	0x42f594	internal/poll.runtime_pollWait+0x54				/Users/mike/.gvm/gos/go1.14.6/src/runtime/netpoll.go:203
#	0x4dcfe4	internal/poll.(*pollDesc).wait+0x44				/Users/mike/.gvm/gos/go1.14.6/src/internal/poll/fd_poll_runtime.go:87
#	0x4dde7a	internal/poll.(*pollDesc).waitRead+0x19a			/Users/mike/.gvm/gos/go1.14.6/src/internal/poll/fd_poll_runtime.go:92
#	0x4dde5c	internal/poll.(*FD).Read+0x17c					/Users/mike/.gvm/gos/go1.14.6/src/internal/poll/fd_unix.go:169
#	0x56d7be	net.(*netFD).Read+0x4e						/Users/mike/.gvm/gos/go1.14.6/src/net/fd_unix.go:202
#	0x57ff3d	net.(*conn).Read+0x8d						/Users/mike/.gvm/gos/go1.14.6/src/net/net.go:184
#	0x6500cf	crypto/tls.(*atLeastReader).Read+0x5f				/Users/mike/.gvm/gos/go1.14.6/src/crypto/tls/conn.go:760
#	0x47ee30	bytes.(*Buffer).ReadFrom+0xb0					/Users/mike/.gvm/gos/go1.14.6/src/bytes/buffer.go:204
#	0x65031b	crypto/tls.(*Conn).readFromUntil+0xeb				/Users/mike/.gvm/gos/go1.14.6/src/crypto/tls/conn.go:782
#	0x64e8d4	crypto/tls.(*Conn).readRecordOrCCS+0x114			/Users/mike/.gvm/gos/go1.14.6/src/crypto/tls/conn.go:589
#	0x6511fc	crypto/tls.(*Conn).readRecord+0x6c				/Users/mike/.gvm/gos/go1.14.6/src/crypto/tls/conn.go:557
#	0x651207	crypto/tls.(*Conn).readHandshake+0x77				/Users/mike/.gvm/gos/go1.14.6/src/crypto/tls/conn.go:973
#	0x66a4d9	crypto/tls.(*serverHandshakeState).doFullHandshake+0x4e9	/Users/mike/.gvm/gos/go1.14.6/src/crypto/tls/handshake_server.go:524
#	0x6684ae	crypto/tls.(*serverHandshakeState).handshake+0x31e		/Users/mike/.gvm/gos/go1.14.6/src/crypto/tls/handshake_server.go:105
#	0x668060	crypto/tls.(*Conn).serverHandshake+0x100			/Users/mike/.gvm/gos/go1.14.6/src/crypto/tls/handshake_server.go:60
#	0x653150	crypto/tls.(*Conn).Handshake+0x1e0				/Users/mike/.gvm/gos/go1.14.6/src/crypto/tls/conn.go:1342
#	0x70ec5c	net/http.(*conn).serve+0x19c					/Users/mike/.gvm/gos/go1.14.6/src/net/http/server.go:1816

```

tinode version 0.16.6

The current number of cluster nodes is 20

**Comment by or-else** [comment] 2020-08-27 16:51
@aforge Could you please take a look at this?

**Comment by aforge** [comment] 2020-08-27 20:19
Somehow we are not garbage collecting topic proxy sessions.
@hhy5861 Can you confirm the number of topics in your setup is in thousands or tens of thousands?

**Comment by aforge** [comment] 2020-08-28 06:52
I can't reproduce it locally on a 3-node setup.
So with ~10000 active local topics, ~2600 websocket sessions, you've got ~278000 proxy connections - which is a little high for a 20-node setup, let alone incoming proxy connections (~626000).

@hhy5861 did this profile result from a natural load over a period of time or some kind of synthetic test? If latter, what did it look like?
Also, would it be possible for you to grab these goroutine profiles from the remaining nodes please?
I'd like to look at the number of topics, number of sessions and and local and remote proxy session distribution.

**Comment by hhy5861** [comment] 2020-08-28 11:26
> I can't reproduce it locally on a 3-node setup.
> So with ~10000 active local topics, ~2600 websocket sessions, you've got ~278000 proxy connections - which is a little high for a 20-node setup, let alone incoming proxy connections (~626000).
> 
> @hhy5861 did this profile result from a natural load over a period of time or some kind of synthetic test? If latter, what did it look like?
 this is the real data of the production environment. This is a sample taken at the time point when a node load is the highest. But the load of other nodes is similar.

> Also, would it be possible for you to grab these goroutine profiles from the remaining nodes please?
I checked the distribution of other nodes are almost the same. The memory usage is still high, mainly because the session recovery mechanism is still problematic. It should be caused by topic proxy.

> I'd like to look at the number of topics, number of sessions and and local and remote proxy session distribution.

![12](https://user-images.githubusercontent.com/8274977/91554937-a1de7900-e962-11ea-82fa-9ba3398848a4.png)
![34](https://user-images.githubusercontent.com/8274977/91554948-a60a9680-e962-11ea-8794-098c0292f868.png)

```
# HELP promhttp_metric_handler_requests_in_flight Current number of scrapes being served.
# TYPE promhttp_metric_handler_requests_in_flight gauge
promhttp_metric_handler_requests_in_flight 1
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 549
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
# HELP spider_cluster_leader If this cluster node is the cluster leader.
# TYPE spider_cluster_leader gauge
spider_cluster_leader 0
# HELP spider_cluster_nodes_live Number of cluster nodes believed to be live by the current node.
# TYPE spider_cluster_nodes_live gauge
spider_cluster_nodes_live 19
# HELP spider_cluster_size Configured number of cluster nodes.
# TYPE spider_cluster_size gauge
spider_cluster_size 20
# HELP spider_malloced_bytes Number of bytes of memory allocated and in use.
# TYPE spider_malloced_bytes gauge
spider_malloced_bytes 1.0655576848e+10
# HELP spider_sessions_live_count Number of currently active sessions.
# TYPE spider_sessions_live_count gauge
spider_sessions_live_count 780081
# HELP spider_sessions_total Total number of sessions since instance start.
# TYPE spider_sessions_total counter
spider_sessions_total 1.307638e+06
# HELP spider_topics_live_count Number of currently active topics.
# TYPE spider_topics_live_count gauge
spider_topics_live_count 498192
# HELP spider_topics_total Total number of topics used during instance lifetime.
# TYPE spider_topics_total counter
spider_topics_total 1.40286e+06
# HELP spider_up If tinode instance is reachable.
# TYPE spider_up gauge
spider_up 1
# HELP spider_version The version of this tinode instance.
# TYPE spider_version gauge
spider_version 1600
```

**Comment by aforge** [comment] 2020-08-29 03:06
https://github.com/tinode/chat/pull/533 should help with this.
I've merged it to devel. You can perhaps patch it in your branch until the next release.

I'm going to close the bug. Feel free to reopen if you still observe this issue.

**Closed by aforge** 2020-08-29 03:06 UTC
Labels: bug
