### ISSUE TITLE
Can you implement self defined RSA encrypted comunication? because maybe everyone don't believe the server.

### ISSUE THREAD

**Issue by naowang** [tinode/chat#626] opened 2021-03-18 21:51 UTC
Can you implement self defined RSA encrypted comunication? because maybe everyone don't believe the server. I am the one don't believe the chat server.

**Comment by or-else** [comment] 2021-03-19 04:36
This is a large feature. Would you like to support it in some way?

**Comment by SongShawn** [comment] 2021-03-27 05:57
That is really a good feature.

**Comment by or-else** [comment] 2021-03-27 19:13
Duplicate of #357

**Closed by or-else** 2021-03-27 19:13 UTC
Labels: feature request
