### ISSUE TITLE
Return the last message along with chat list

### ISSUE THREAD

**Issue by kisulken** [tinode/chat#346] opened 2020-01-29 19:27 UTC
This is probably a feature request as I was not able to locate a function to return the last messages with the list of chats aside from requesting everyone of them separately. 

Currently the chat list looks like a list of names when most of the modern messengers are also displaying the last messages of the dialog along with the recipient name. 

For example: list of chats in telegram containing name of a recipient and the last message of a dialog.
![785DEBB7-4912-477F-9478-8C60B817AC62](https://user-images.githubusercontent.com/7709243/73389630-75a63100-4289-11ea-9a80-153811bc64d0.png)

**Comment by or-else** [comment] 2020-01-30 06:16
Duplicate of https://github.com/tinode/chat/issues/307

**Closed by or-else** 2020-01-30 06:16 UTC
Labels: duplicate, feature request
