### ISSUE TITLE
Syntax error when initiating MySql database

### ISSUE THREAD

**Issue by tech-Nico** [tinode/chat#222] opened 2019-02-24 20:29 UTC
### Subject of the issue
I'm trying to deploy Tinode on a one node kubernetes cluster and I already have MySql 5.6 running in a pod that I'm using to serve Wordpress.
When I try to initiate the DB I'm getting the following error:
`/opt/tinode # ./init-db --reset=true --config=/tinode.conf --data=data.json
2019/02/24 10:02:01 Database reset requested
2019/02/24 10:02:01 Failed to init DB:Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'JSON,
			lastseen  DATETIME,
			useragent VARCHAR(255) DEFAULT '',
			public    ' at line 7
`

However, if I run the init-db with --reset=false I get the following message:
`/opt/tinode # ./init-db --reset=false --config=/tinode.conf --data=data.json
2019/02/24 20:18:29 Database exists, DB version is correct. All done. mysql
`

which makes me think the issue is not with mysql version.
Am I doing something wrong?

### Is this a bug report of a feature request?
- [x] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * platform (Windows, Mac, Linux etc) : Centos 7 / Microk8s kubernetes node
  * version of tinode server, e.g. `0.15.2-rc3` : `0.15.12` and `latest`
  * database backend: My SQL

### Server-side Log
`2019/02/24 10:02:01 Failed to init DB:Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'JSON,
			lastseen  DATETIME,
			useragent VARCHAR(255) DEFAULT '',
			public    ' at line 7`

**Comment by or-else** [comment] 2019-02-25 03:02
Here is a quote from tinode/chat/INSTALL.md:

> MySQL 5.7 or above is required. MySQL 5.6 or below will not work.

**Comment by tech-Nico** [comment] 2019-02-25 09:37
Thanks @or-else 
I should definitely RTFM (face of shame).. but then, why is init-db telling me the DB version is correct?

**Comment by or-else** [comment] 2019-02-25 11:04
```
/opt/tinode # ./init-db --reset=false --config=/tinode.conf --data=data.json 
2019/02/24 20:18:29 Database exists, DB version is correct. All done. mysql
```
I see why it's happening. It's a bug. Thanks!

**Comment by or-else** [comment] 2019-02-25 13:55
Actually I cannot reproduce. Could you please execute from the same DB instance where you saw the wrong 'Database exists, DB version is correct. All done. mysql':
```
SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME LIKE 'tinode';
```
and if `tinode` db exists then also
```
SHOW TABLES FROM tinode;
```
Thanks!

**Comment by or-else** [comment] 2019-02-25 14:05
Please disregard the previous message. The reason why you got `Database exists, DB version is correct. All done. mysql` is due to the way MySQL 5.x handles transactions. It implicitly commits a transaction on `CREATE TABLE`:
https://dev.mysql.com/doc/refman/5.6/en/implicit-commit.html
It created the `tinode` database and `kvmeta` table then failed on the next table. Unfortunately it auto-committed the creation of `kvmeta`. The subsequent run checked the schema version by reading from `kvmeta`, found it to be correct and exited.  

I'll move `kvmeta` creation to the end of the process.

**Comment by or-else** [comment] 2019-03-04 09:01
[Released](https://github.com/tinode/chat/releases/tag/v0.15.13-rc3)

**Closed by or-else** 2019-03-04 09:01 UTC
