### ISSUE TITLE
Video or audio calling

### ISSUE THREAD

**Issue by HeroSony** [tinode/chat#765] opened 2022-06-20 06:46 UTC
Hello, I see you planned to release these features https://github.com/tinode/chat#planned, so far for video or audio calls, are you doing it? if not yet, do you have ideas or resources on how to apply this feature?

**Comment by or-else** [comment] 2022-06-20 15:23
Duplicate of #150

See here: https://github.com/tinode/chat/releases/tag/v0.20.0-beta2

**Closed by or-else** 2022-06-20 15:23 UTC
Labels: feature request
