### ISSUE TITLE
 Cannot publish on inactive topic

### ISSUE THREAD

**Issue by xingguangkuo** [tinode/chat#110] opened 2018-06-20 04:05 UTC
1:1 chat 
my code：
    var t111 =Tinode.Tinode.getTopic("usrctNBS3OGhFE");
    t111.publish("1122",undefined,"text/plain")
          .then(function(ctrl) {
          console.info(ctrl);
        });
        }).catch(function(err) {
          // Login or subscription failed, do something.
          console.info(err);
        });

error log：
    tinode.js?723e:2428 Uncaught (in promise) Error: Cannot publish on inactive topic
    at Topic.publish (tinode.js?723e:2428)
    at eval (App.vue?26cd:138)
    at <anonymous>

Why does this topic have no subscription？ How to use topic to send messages？
How Tinode JS uses attaching session to a topic？ Thank you！

**Comment by or-else** [comment] 2018-06-20 05:20
Duplicate of #109

**Closed by or-else** 2018-06-20 05:20 UTC
