### ISSUE TITLE
Tinode cluster in Kubernetes

### ISSUE THREAD

**Issue by ysaakpr** [tinode/chat#410] opened 2020-04-06 10:34 UTC
### Tinode Clustering in Kubernetes
What is the way to deploy Tinode cluster in Kubernetes? Given that the Tinode stores the messages external storage engine like MySQL or RethinkDB, It would be easier to run Tinode in Kubernetes as stateless nodes joining a cluster for HA. But Ii could not find any suggested way to do that in the forum. Any thoughts?

1. How to Dynamically increase the number of Tinode nodes
2. Should be stateful set or a Deployment?

**Comment by or-else** [comment] 2020-04-06 12:28
Duplicate of #316

**Comment by or-else** [comment] 2020-04-06 12:29
As stated in #316, deploying Tinode with k8s makes no sense to me because k8s expects stateless identical pods. 

1. Not possible right now. Maybe added in the future.
2. I don't understand the question.

**Comment by or-else** [comment] 2020-04-07 11:57
I reopened #316. Please use it to continue this discussion.

**Closed by or-else** 2020-04-07 11:57 UTC
Labels: question
