### ISSUE TITLE
Get a list of other users blocked by current user

### ISSUE THREAD

**Issue by kigvshi2** [tinode/chat#423] opened 2020-04-16 16:06 UTC
### Is this a bug report of a feature request?
- [*] Feature request

#### Server-side
- [*] api.tinode.co
- [*] Your own setup:
  * platform (Windows, Mac, Linux etc)
  * version of tinode server, e.g. `0.15.2-rc3`
  * database backend
  
#### Client-side
- [*] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
- [*] Tindroid: Android app
  * Android API level (e.g. 25).
  * Emulator or hardware, if hardware describe it.
- [*] tn-cli
  * Python version
- [*] Chatbot
  * Python version
- Version of the client, e.g. `0.15.1`

Based on [https://groups.google.com/forum/#!topic/tinode/2yla_6_WeVQ ](https://groups.google.com/forum/#!topic/tinode/2yla_6_WeVQ) i want to get a list of users blocked by current user but there is no such api;

**Comment by or-else** [comment] 2020-04-17 07:31
> but there is no such api;

The problem is not the API. The server returns the full list of users, including blocked users. The problem is that clients currently just hide blocked users.

**Comment by or-else** [comment] 2020-04-17 11:31
I've implemented it in webapp:
https://github.com/tinode/webapp/commit/e5e78755ae2bcbb7a9cfa141062bd5ff50d580f7
You are welcome to take a shot at iOS or Android clients.

**Comment by or-else** [comment] 2020-07-07 19:21
Released in all official clients.

**Closed by or-else** 2020-07-07 19:21 UTC
Labels: feature request
