### ISSUE TITLE
Postgres database does not created if it's not named as tinode

### ISSUE THREAD

**Issue by Makashov** [tinode/chat#860] opened 2023-05-02 18:37 UTC
### PostgreSQL migration
When I compile and run tinode-db using PostgreSQL and set the database name in tinode.conf to something other than 'tinode', the database is not created and program panics.

#### Server-side
- [x] Your own setup:
  * platform (Mac)
  * version of Tinode server, v0.22.7`
  * database backend postgres adapter version 113
  * standalone

#### Client-side
- [x] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
  * IMPORTANT! Use `index-dev.html` to reproduce the problem, not `index.html`.

### Steps to reproduce
Rename database name in `tinode-db/tinode.conf` to something other than **tinode**.
Run **tinode-db** binary file.

### Expected behaviour
Create database specified in `tinode-db/tinode.conf` if it  doesn't exists. And all required tables.

### Actual behaviour
Program panics without any explanation of the error. Just a debug information from panic.

### Server-side log
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x133e05d]

goroutine 1 [running]:
github.com/jackc/pgx/v4/pgxpool.(*Pool).Acquire(0x0, {0x147fd40, 0xc0001a4008})
        /Users/nurbol/go/pkg/mod/github.com/jackc/pgx/v4@v4.18.1/pgxpool/pool.go:532 +0x3d
github.com/jackc/pgx/v4/pgxpool.(*Pool).QueryRow(0x0?, {0x147fd40, 0xc0001a4008}, {0x13f0a78, 0x27}, {0xc000191a30, 0x1, 0x1})
        /Users/nurbol/go/pkg/mod/github.com/jackc/pgx/v4@v4.18.1/pgxpool/pool.go:641 +0x55
github.com/tinode/chat/server/db/postgres.(*adapter).GetDbVersion(0xc0001a2660)
        /Users/nurbol/Documents/go/tinode-chat/server/db/postgres/adapter.go:217 +0xf7
github.com/tinode/chat/server/store.storeObj.GetDbVersion(...)
        /Users/nurbol/Documents/go/tinode-chat/server/store/store.go:170
main.main()
        /Users/nurbol/Documents/go/tinode-chat/tinode-db/main.go:245 +0x999
```

### Client-side log
Have no logs

**Comment by Makashov** [comment] 2023-05-02 18:51
I found that in `server/db/postgres/adapter.go`  there is an **if/else** statement where is the database name is hardcoded I guess.
```go
// Ignore missing database here. If we are initializing the database
// missing DB is OK.
if a.poolConfig.ConnConfig.Database == "tinode" {
	a.poolConfig.ConnConfig.Database = "postgres"
	a.db, err = pgxpool.ConnectConfig(ctx, a.poolConfig)
}
```
I tried to change the **tinode** string to the actual name of my database and it worked as I expected. But since I am very new in this project and in golang development I am not sure for what this statement for. 
I also can't understand what `a.poolConfig.ConnConfig.Database = "postgres"` does.

P.S. Thank you for your great work!

**Comment by or-else** [comment] 2023-05-02 21:11
Thanks, fixed in https://github.com/tinode/chat/commit/52f33fe301cf2ac4403e0c62c80a0f1b28139493

**Comment by or-else** [comment] 2023-05-04 21:25
Have you had a chance to verify?

**Comment by Makashov** [comment] 2023-05-05 09:56
For some reason it tries to create database named **tinode**. As I understood it gets it from `defaultDatabase` constant.

**Comment by Makashov** [comment] 2023-05-05 10:02
Ok I got it. It happens only when `postgres.dsn` is used in configs. But if you use the `DBName` everything is fine.

**Comment by or-else** [comment] 2023-05-06 01:56
Can you share your config? I cannot reproduce.

**Comment by or-else** [comment] 2023-05-06 02:11
I removed some unnecessary logic: https://github.com/tinode/chat/commit/b7817c7dfca5c71e184be485eedaa684a01547d4
Please see if the problem persists.

**Comment by Makashov** [comment] 2023-05-06 22:03
My config is below. Notice I specified database name as **my_db** but it created database named **tinode**:
```json
{
	"store_config": {
		"uid_key": "la6YsO+bNX/+XIkOqc5Svw==",
		"use_adapter": "",
		"adapters": {
			"postgres": {
				"dsn": "postgresql://postgres:postgres@localhost:5432/my_db?sslmode=disable"
			},
			"mysql": {
				"database": "tinode",
				"dsn": "root@tcp(localhost)/tinode?parseTime=true&collation=utf8mb4_unicode_ci"
			},
			"rethinkdb": {
				"database": "tinode",
				"addresses": "localhost:28015"
			},
			"mongodb": {
				"database": "tinode",
				"addresses": "localhost:27017"
			}
		}
	}
}
```

**Comment by or-else** [comment] 2023-05-06 22:14
That's expected. For historical reasons in addition to DSN, the config also needs to specify the database name separately as `dbname`. I'll see how hard it would be to fix it.

**Comment by Makashov** [comment] 2023-05-06 22:24
Yes worked after adding `"DBName": "my_db"`

**Comment by or-else** [comment] 2023-05-07 00:48
I removed the requirement for specifying db name in addition to DSN: https://github.com/tinode/chat/commit/8491f05fdc4acd0f13b6b602ff59c6a0fc6b4a9b
DSN alone is now enough.

**Comment by or-else** [comment] 2023-05-08 17:54
I assume everything is fixed here and working as expected. If not, please let me knwo.

**Closed by or-else** 2023-05-08 17:54 UTC
Labels: bug
