### ISSUE TITLE
Presence packets clarification

### ISSUE THREAD

**Issue by jaylevin** [tinode/chat#104] opened 2018-06-08 23:54 UTC
Hi, this isn't really a bug, but more likely a misunderstanding on my part.

The API documentation reads:

> When user's me topic comes online (i.e. an authenticated session attaches to me topic), a {pres} packet is sent to me topics of all other users, who have peer to peer subscriptions with the first user.

My interpretation: User A is subscribed (and attached) to user B. User A is online and user B is offline.

User B logins in, and subscribes to their `me` topic.

User A receives a `{pres}` packet.

Currently, the only time I am seeing a `{pres}` packet show up, is when a user subscribes (and attaches) to another user for the first time.

Thanks for your time.

**Comment by or-else** [comment] 2018-06-09 05:18
> My interpretation: User A is subscribed (and attached) to user B. User A is online and user B is offline. User B logins in, and subscribes to their me topic. User A receives a {pres} packet.

That's correct interpretation and that's how it works. I just double checked both devel and api.tinode.co. Both work exactly as expected, {pres what="on"} is correctly sent.

> Currently, the only time I am seeing a {pres} packet show up, is when a user subscribes (and attaches) to another user for the first time.

If you don't see the {pres what="on"} when B attaches to me topic, then it's a bug. I cannot reploduce it though. Please provide exact steps to reproduce. Thanks.

**Comment by jaylevin** [comment] 2018-06-09 17:37
I just noticed that when I was "logging out", I was only exiting the gRPC MessageLoop
`2018/06/09 10:30:52 grpc.MessageLoop - stop`, and not sending any `{leave}` messages.

This probably has something to do with it... Can you confirm?

I'd imagine we need to send a `{leave}` before the tinode server could send a `{pres what="OFF"}`.

Thanks

**Comment by or-else** [comment] 2018-06-09 17:44
`{pres what="off"}` should be issued within 5 seconds of leaving regardless of you disconnecting gracefully or just closing the application. Could you please show the client- and server-side logs. Also, please confirm that the test user does not have another session open.

**Comment by jaylevin** [comment] 2018-06-09 17:53
Starting with a fresh server running, no sessions:
I login with user A (which already has a subscription to another user B), and attach to the only other subscription user A has, as well as the `me` topic.
`2018/06/09 10:46:53 Listening for client HTTP connections on [:6060]
2018/06/09 10:46:57 hi:<id:"1" user_agent:"Golang_Spider_Bot/3.0" ver:"0.15" lang:"EN" >
2018/06/09 10:46:57 grpc: writing message to stream ctrl:<id:"1" code:201 text:"created" params:<key:"build" value:"\"mysql:undef\"" > params:<key:"ver" value:"\"0.15\"" > >
2018/06/09 10:46:57 login:<id:"112121" scheme:"basic" secret:"Jordan:" >
2018/06/09 10:46:57 grpc: writing message to stream ctrl:<id:"112121" code:200 text:"ok" params:<key:"authlvl" value:"\"auth\"" > params:<key:"expires" value:"\"2018-06-23T17:46:57.746Z\"" > params:<key:"token" value:"\"EebrdESBTRqRhy5bFAABAAEAb29XssUupAO8S+87VzP8KYlat99xxYa3dlZhd3C9ILY=\"" > params:<key:"user" value:"\"usrEebrdESBTRo\"" > >
2018/06/09 10:46:57 sub:<topic:"me" >
2018/06/09 10:46:57 Sub to 'me' from 'usrEebrdESBTRo'
2018/06/09 10:46:57 hub: topic created or loaded: usrEebrdESBTRo
2018/06/09 10:46:57 Topic started: 'usrEebrdESBTRo'
2018/06/09 10:46:57 grpc: writing message to stream ctrl:<topic:"me" code:200 text:"ok" >
2018/06/09 10:46:57 get:<topic:"me" query:<what:"sub" > >
2018/06/09 10:46:57 s.get: processing 'get.sub'
2018/06/09 10:46:57 grpc: writing message to stream meta:<topic:"me" sub:<updated_at:1528565166844 acs:<want:"JRW" given:"JRWA" > public:"{\"FN\":\"Test123\",\"Photo\":null}" private:"null" topic:"usr9VoyZ5pfBKQ" touched_at:1528565166844 last_seen_time:1528566336000 last_seen_user_agent:"Golang_Spider_Bot/3.0" > >
2018/06/09 10:46:57 sub:<topic:"usr9VoyZ5pfBKQ" >
2018/06/09 10:46:57 Sub to 'usr9VoyZ5pfBKQ' from 'usrEebrdESBTRo'
2018/06/09 10:46:57 hub: existing p2p topic
2018/06/09 10:46:57 hub: topic created or loaded: p2pEebrdESBTRr1WjJnml8EpA
2018/06/09 10:46:57 Topic started: 'p2pEebrdESBTRr1WjJnml8EpA'
2018/06/09 10:46:57 grpc: writing message to stream ctrl:<topic:"usr9VoyZ5pfBKQ" code:200 text:"ok" >`

I then login with user B, which is the only p2p subscription user A has, `usr9VoyZ5pfBKQ`:
`2018/06/09 10:50:47 hi:<id:"1" user_agent:"Golang_Spider_Bot/3.0" ver:"0.15" lang:"EN" >
2018/06/09 10:50:47 grpc: writing message to stream ctrl:<id:"1" code:201 text:"created" params:<key:"build" value:"\"mysql:undef\"" > params:<key:"ver" value:"\"0.15\"" > >
2018/06/09 10:50:47 login:<id:"112121" scheme:"basic" secret:"Test123:" >
2018/06/09 10:50:47 grpc: writing message to stream ctrl:<id:"112121" code:200 text:"ok" params:<key:"authlvl" value:"\"auth\"" > params:<key:"expires" value:"\"2018-06-23T17:50:47.283Z\"" > params:<key:"token" value:"\"9VoyZ5pfBKR3iC5bFAABAAEAWcXlN2eKmPZwlyW3nKyfwPWTmLIYE26gS4srvhrftnQ=\"" > params:<key:"user" value:"\"usr9VoyZ5pfBKQ\"" > >
2018/06/09 10:50:47 sub:<topic:"me" >
2018/06/09 10:50:47 Sub to 'me' from 'usr9VoyZ5pfBKQ'
2018/06/09 10:50:47 hub: topic created or loaded: usr9VoyZ5pfBKQ
2018/06/09 10:50:47 Topic started: 'usr9VoyZ5pfBKQ'
2018/06/09 10:50:47 grpc: writing message to stream ctrl:<topic:"me" code:200 text:"ok" >
2018/06/09 10:50:47 get:<topic:"me" query:<what:"sub" > >
2018/06/09 10:50:47 s.get: processing 'get.sub'
2018/06/09 10:50:47 grpc: writing message to stream meta:<topic:"me" sub:<updated_at:1528565166844 online:true acs:<want:"JRWA" given:"JRW" > public:"{\"FN\":\"Jordan\",\"Photo\":null}" private:"null" topic:"usrEebrdESBTRo" touched_at:1528565166844 > >
2018/06/09 10:50:47 sub:<topic:"usrEebrdESBTRo" >
2018/06/09 10:50:47 Sub to 'usrEebrdESBTRo' from 'usr9VoyZ5pfBKQ'
2018/06/09 10:50:47 grpc: writing message to stream ctrl:<topic:"usrEebrdESBTRo" code:200 text:"ok" >`

5 seconds later and no other server messages for the client to provide any useful logs. Correct me if I'm wrong, but there should be a {pres} message emitted in the server console? (and intercepted by user A client)

**Comment by or-else** [comment] 2018-06-09 18:21
> acs:<want:"JRW" given:"JRWA" > public:"

The P permission is missing. Essentially you disabled presence notifications for one of the users.

**Comment by jaylevin** [comment] 2018-06-09 19:19
Thank you very much. Still need to figure out permissions

**Comment by or-else** [comment] 2018-06-10 05:37
I assume the issue is resolved. If not, feel free to comment or create a new one.

**Closed by or-else** 2018-06-10 05:37 UTC
Labels: incomplete

**Comment by jaylevin** [comment] 2018-06-10 23:27
Okay so that worked wonderfully, however now when I send a message to a user that is not subscribed back to me, they do not receive a `{data}` message- They DO however receive a `{pres topic:"me" src:"usr9UbG3tEM2RY" what:MSG seq_id:1}`. I've tried setting ACS modes to `JRWPA` and `JRWPAS` with no success.

Thank you for your help.

**Comment by or-else** [comment] 2018-06-11 05:52
> however now whenever I send a message to a user that is not subscribed back to me, they do not receive a {data} message-

That's the way it's supposed to work. If you want to receive `{data}` messages you should subscribe back. If you are not subscribed back all you are going to get is the notifications.

What is your use case? What are you trying to achieve?

**Comment by jaylevin** [comment] 2018-06-11 15:21
Ah, thank you. I am integrating tinode into a basic client desktop application ran on Go. Just was a little confused on how I was going to store the messages if the user is not subscribed back. I can find a work around though if this is how it is supposed to work. I could've sworn I remembered previously seeing {data} packets on both sides regardless of subscription, but I guess I am mistaken.

Thank you for clarifying.

**Comment by or-else** [comment] 2018-06-11 15:33
Users can fetch all or just the new messages when they come online. The messages are stored on the server.

**Comment by jaylevin** [comment] 2018-06-12 21:55
I have some questions on loading message history for a user's topics when they login:

Currently, I'm performing a `{get topic="me" what="sub"}` to get an array of topics the user is subscribed to.
After that, I perform a `{get topic:"..." what="data"}` on each topic ID in the array. At first, this gave me an error `s.get: subscribe first to get 'data'` which doesn't make sense to me.

If I loaded these topics from the user's subscribed list, shouldn't the user already be subscribed.

I went ahead and threw in a `sub topic="..."` mon each of the topic IDs in the user's subscription list which is loaded as soon as they authenticate. Still the same error.... This was working earlier

Thank you for your time

**Comment by jaylevin** [comment] 2018-06-12 23:03
I have a simple question. My current method of fetching and rendering message history on login goes like this:

1. User logs in and authenticates successfully, subscribes to `me` topic
2. User sends `{get topic="me" what="sub"}` to return a list of their subscriptions to other users/groups
3. I then loop through this list, calling `{sub topic="..."}` for each topic ID in the list to subscribe the user to each of their topics that they've already subscribed to
4. Finally, user sends `{get topic="..." what="data"}` for each topicID in the list.

**My questions:**
1. Is this a proper procedure for loading the message history for a user's subscription list?
2. Why do I have to send a `sub` to each of the topic IDs within the user's subscription list in order to get their data?

**Comment by or-else** [comment] 2018-06-13 05:20
I don't understand your use case. Is it an interactive application? Some background sync service?
If the former, then you don't need to fetch everything every time. Fetch only those topics and messages which the user interacts with. If the latter, then you should have a local cache of topics and messages. There is no need to re-fetch everything on every connection. 

Specifically, regarding your steps:
1. Correct.
2. Correct with a caveat. If you have local cache of subscriptions, use `ims` to fetch only changed subscriptions.
3. You can do it this way but it looks inefficient. You can use `seq` to check if the topic has new messages and only fetch those.
4. Can be done this way but seems awfully wasteful. Like in step 4, you should be able to tell which messages you have by `seq` value and then fetch new messages only.

> Why do I have to send a sub to each of the topic IDs within the user's subscription list in order to get their data if the topics are already in the user's me topic (subscription list)?

This is a form of resource management. You seem to be doing something which I don't understand and maybe what Tinode was not intended for. As I said, I don't understand your use case. 

Why do you need to fetch everything on every connection?

**Comment by jaylevin** [comment] 2018-06-13 17:37
It is a simple GUI interactive desktop application, similiar to the javascript demo you have. I see, so basically the `ims` and `seq` features are intended to be binded to a local database/cache in order to keep track of what topics/messages are "new" to each client?

**Comment by or-else** [comment] 2018-06-13 19:12
> I see, so basically the ims and seq features are intended to be binded/synced to a local (client side) database/cache, which keeps track of which messages/topics are "new"?

Correct.
