### ISSUE TITLE
Cannot get latest group topic

### ISSUE THREAD

**Issue by wmshek1992** [tinode/chat#604] opened 2021-01-18 06:41 UTC
### Cannot get latest group topic
One of my user has 1085 topics, most of them are group topics and a few p2p topics.
I tried to use {sub: {ims: "2021-01-06T18:07:30.038Z"}} to limit the result.
I expect the result would only consist of topics that their "updated" are after "ims", but it failed to work. 
So what is the correct way to obtain a response with latest topics

#### Server-side
  * version of Tinode server 0.16.4
  * database backend : MySQL
  * standalone

**Comment by or-else** [comment] 2021-01-18 17:51
Yes, it's a design limitation. In the short term you can change this line and recompile:
https://github.com/tinode/chat/blob/master/server/db/mysql/adapter.go#L42
I'll fix it in the next release.

**Comment by or-else** [comment] 2021-01-18 18:00
Actually, you don't need to recompile. Set max_results in store config:
https://github.com/tinode/chat/blob/master/server/tinode.conf#L174

Set it to something like 2000 and restart the server

**Comment by wmshek1992** [comment] 2021-01-19 05:56
Yes, I increased the limit in the config file. But potentially it could be exceeded in long term, and also the result can be huge. 

I would like to limit the topic list result by it's updated time such that clients can get the latest topics. Is it an existing feature or a new feature request?

**Comment by or-else** [comment] 2021-01-19 16:24
As I said in my previous message, I'll fix it in 0.17

**Comment by or-else** [comment] 2021-04-05 03:50
The same as #342

**Comment by or-else** [comment] 2021-04-12 16:17
The `ims` in `{get what=subs}` is now respected. The clients are not updated to use it but the server will paginate the subscriptions by `ims`.

**Comment by or-else** [comment] 2021-04-12 16:18
I'm closing this, please continue further discussion in #342.

**Comment by or-else** [comment] 2021-04-12 16:18
Duplicate of #342.

**Closed by or-else** 2021-04-12 16:18 UTC
Labels: bug
