### ISSUE TITLE
Topic stuck for receiving user in p2p/grp

### ISSUE THREAD

**Issue by dilshansdoq** [tinode/chat#866] opened 2023-05-27 20:34 UTC
### Subject of the issue
Hi,
This seems like a bug. So we have slightly changed the client implementation such that if a user receives `pres` with `what:msg` indicating someone has messaged this user, will fetch that message and mark delivery (sub:topic:get:what:data -> note:recv -> leave:topic), and this will happen for each message pres received.
After some time of messaging, topic gets stuck for the user at receiving end of messages, such that user is not receiving any pres message(indicating not subbed to topic) nor any data messages(indicating subbed to topic). This user is not receiving anything happening in this topic. Also <server>/debug/status show user is already subscribed to topic. 
This gets fixed if user sends another leave:topic request. 

#### Server-side
- [x] Your own setup:
  * platform: Linux
  * version of Tinode server: 0.21 + (some cherry picks from devel)
  * database backend: mongodb
  * standalone

#### Client-side
- [x] TinodeWeb/tinodejs: javascript client
  * Browser make and version: Microsoft edge Version 113.0.1774.35 (Official build) (64-bit)
- [x] Tindroid: Android app
  * Android API level 30,31,32,33
  * Hardware: Latest 2022-2023 flagships
- Version of the client, e.g. `0.21.0`
- [x] Your own client. Describe it:
  * Transport: ws
  * Testing script with NodeJS 

### Steps to reproduce
This issue isn't 100% reproducible. It takes many tries and happens randomly (my intuition is something is happening when subbing and leaving). However i have written a script replicating what would happen when a user (on receiving end) receives pres:what:msg and does (sub:topic:get:what:data -> note:what:recv -> leave:topic). 
[topic-stuck-issue.zip](https://github.com/tinode/chat/files/11582990/topic-stuck-issue.zip)

### Expected behaviour
User should be able to receive either {pres} or {data}.

### Actual behaviour
User is not receiving neither {pres} nor {data}

### Server-side log
[topic-stuck-server.log](https://github.com/tinode/chat/files/11582970/topic-stuck-server.log)

### Client-side log
Receving side: 
I have manually put some comments where topic was stuck for receiving user and was not receiving any updates.
[topic-stuck-client.log](https://github.com/tinode/chat/files/11582972/topic-stuck-client.log)

**Comment by or-else** [comment] 2023-05-27 21:45
@aforge This sounds like something related to `Session.inflightReqs`. Would you take a look?

**Comment by dilshansdoq** [comment] 2023-06-14 19:32
Hi, any update on this issue?

**Comment by aforge** [comment] 2023-07-05 21:02
Sorry for delay. This somehow fell below my radar.
I haven't been able to reproduce the issue fully but it looks like a race condition around https://github.com/tinode/chat/blob/master/server/session.go#L149 from what I've been able to figure out.
I keep looking...

**Comment by or-else** [comment] 2023-07-10 16:10
Released in 0.22.9

**Closed by or-else** 2023-07-10 16:10 UTC
Labels: bug
