### ISSUE TITLE
Sensitive information in the logs

### ISSUE THREAD

**Issue by kisulken** [tinode/chat#653] opened 2021-05-26 07:53 UTC
By default tinode logs everything in `/var/log/tinode.log` including secrets, messages, topic descriptions etc

1. How to disable/limit the log output? At least in production we really shouldn't log messages and secrets
2. Do we really need to log secrets? Like `'{"login":{"id":"73280","scheme":"basic","secret":"MTIzOmYxMzdhZWYzNWYwMzViMzE="}}' sid='wDTk-dWaTK4' uid=''`

**Comment by or-else** [comment] 2021-05-26 16:58
Duplicate of https://github.com/tinode/chat/issues/215

**Closed** 2021-05-26 16:59 UTC
Labels: question
