### ISSUE TITLE
[Question]deploy on kubernetes

### ISSUE THREAD

**Issue by diaobrother** [tinode/chat#316] opened 2019-11-20 11:36 UTC
On kubernetes, every node is the same. In this case, how to make communication between nodes?

**Comment by or-else** [comment] 2019-11-20 11:41
We con't use k8s exactly for this reason. We deploy three docker containers using docker-compose.

**Comment by ysaakpr** [comment] 2020-04-06 10:29
Does this mean tinode shall not be deployed on Kubernetes? I believe, the application should not restrict the deployment infrastructure. Due to increased adoption of Kubernetes, it would be better to publish the way to deploy on Kubernetes, Possible ways of cluster discovery
1. Can use service dns to discover all the IP addresses which serving at a point in time.
2. A discovery announcer agent can be used as a side can which frequent;y poll either service or pods for getting all the cluster nodes which are not joined the cluster and can add to all the cluster.
3. A state can be maintained separately using things like consul or etcd and can figureout cluster using the state from them.

**Comment by or-else** [comment] 2020-04-06 12:26
As I wrote earlier, deploying Tinode with k8s makes no sense to me because k8s expects stateless identical pods. K8s is a wrong tool for the job. But of course you are welcome to deploy it with k8s if you see a use case for yourself.

1. This is true but not relevant.
2. Cluster nodes must be configured ahead of time to discover each other. Tinode is not stateless like a web server. 
3. I don't think so.

**Comment by Tonkonozhenko** [comment] 2020-04-07 11:45
@or-else we are going to use tinode soon. And I'd like to deploy it in k8s. I'm going to use external DB for storage, s3 for assets. what other stateful stuff do you have that you say it's not possible to deploy it in k8s?

**Comment by or-else** [comment] 2020-04-07 11:54
If you are deploying a cluster then every node maintains a state

**Comment by or-else** [comment] 2020-04-07 11:56
Each node is different from every other cluster node. Like when you run a mysql server, you don't deploy multiple pods with the same database, right? Same here. 

If you are deploying a standalone server, then you can use k8s to deploy a single instance of it.

**Comment by Tonkonozhenko** [comment] 2020-04-07 12:01
@or-else I found a guide [here](https://github.com/tinode/chat/blob/master/INSTALL.md#running-a-cluster) that tells that we need names for each node.
My suggestion is to deploy it using k8s stateful sets with fixed names.

**Comment by or-else** [comment] 2020-04-07 12:05
Sure, please do it and share your experience.

**Comment by Tonkonozhenko** [comment] 2020-04-07 13:13
@or-else sure, I will. Does tinode have something stored in FS so I need put it to volume?

**Comment by or-else** [comment] 2020-04-07 13:35
If you use s3 for user-generated content, then the only thing it reads from the file system is static config (read-only).

**Comment by ysaakpr** [comment] 2020-04-08 10:35
1. We will be using External storage for data
2. s3 for asset

So why do we really need even stateful sets, if we can manage the cluster to work with auto-discovery of nodes?

Actually this means tinode is not stateful by design. Can you make correct if is m missing something? As per my experiments on configs, only the node hostnames and name for it is what changes between config also. Am I missing something?

**Comment by or-else** [comment] 2020-04-08 11:35
> So why do we really need even stateful sets, if we can manage the cluster to work with auto-discovery of nodes?

Because data is sharded between nodes. Each node serves a shard of data. When user connects to a node `N` and subscribes to topic `T`, `T` may be located at another node, say node `M`. So, node `N` will act as a proxy for node `M`. 

> Actually this means tinode is not stateful by design

I'm not sure what meaning you assign to this statement.

**Comment by ysaakpr** [comment] 2020-04-08 11:57
> Because data is sharded between nodes. Each node serves a shard of data. When user connects to a node `N` and subscribes to topic `T`, `T` may be located at another node, say node `M`. So, node `N` will act as a proxy for node `M`.

So even when we use external data storage like Postgres, the in-flight data sharded between nodes? I am missing something on the internal architecture, I guess.

**Comment by ysaakpr** [comment] 2020-04-08 12:36
I also worried, what happens in case of a node failure. If the nodes are maintaining shards of data, (nowhere mentioned replication or leader for the topics) how the system handles high availability of topics?

**Comment by or-else** [comment] 2020-04-08 14:20
> So even when we use external data storage like Postgres

DB is used as dumb storage. All the logic is in the code, all live topics, sessions are in memory.

> I also worried, what happens in case of a node failure

Cluster reconfigures itself, reshards the data and continues to run.

**Comment by ysaakpr** [comment] 2020-04-10 09:15
Then a stateful set should work well, let me try it.

**Comment by haorenfsa** [comment] 2020-11-23 14:18
stateful set + custom resource definition, a Tinode operator like redis or mysql’s operator that maintains the cluster (like expand the cluster or replace a down node) will do.

**Comment by haorenfsa** [comment] 2020-11-23 14:19
> Then a stateful set should work well, let me try it.

@ysaakpr how’s it going?

**Closed** 2021-04-05 03:44 UTC
Labels: question

**Comment by ChrisTomAlx** [comment] 2022-05-23 06:55
Hey! Did anyone end up creating a kubernetes deployable, if so would it be possible to share whether it worked as expected?

**Comment by Spybull** [comment] 2022-10-31 09:37
> Hey! Did anyone end up creating a kubernetes deployable, if so would it be possible to share whether it worked as expected?

https://github.com/Spybull/tinode-helm
and container
https://github.com/Spybull/containers
Work for mongodb, but still needs improvement for other databases and some config

**Comment by kaustubhbabar5** [comment] 2026-04-22 05:14
@or-else while I agree tinode is not stateless and partially stores state on the application layer, I think we can still deploy this on k8s. spicedb is a similar project which can be deployed to k8s. I think we can solve this by using Kubernetes EndpointSlice resources instead of static `cluster_config.nodes` list. Let me know if I can propose a plan to solve this

ref: [Consistent Hash Load Balancing for gRPC](https://authzed.com/blog/consistent-hash-load-balancing-grpc)

**Comment by or-else** [comment] 2026-04-22 06:10
Send a pull request.

**Comment by or-else** [comment] 2026-04-22 06:17
And you may also open a new issue if anything needs to be discussed.
