### ISSUE TITLE
Tinode external authenticator

### ISSUE THREAD

**Issue by wmshek1992** [tinode/chat#403] opened 2020-03-27 10:48 UTC
### How to enable the external authenticator?
I am checking how to implement the REST or JSON-RPC authenticator here: https://github.com/tinode/chat/tree/master/server/auth/rest

I am not sure where to put the configuration in.

Can anyone help me please?

**Comment by or-else** [comment] 2020-03-27 11:05
Duplicate of #401

**Closed by or-else** 2020-03-27 11:05 UTC
