### ISSUE TITLE
flutter client？

### ISSUE THREAD

**Issue by jinfagang** [tinode/chat#703] opened 2021-10-10 07:39 UTC
**If you are not requesting a feature, please post to https://groups.google.com/d/forum/tinode instead.**
---

**Is your feature request related to a problem? Please describe.**

flutter client？

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by or-else** [comment] 2021-10-10 20:01
Duplicate of https://github.com/tinode/chat/issues/250

**Closed by or-else** 2021-10-10 20:01 UTC
Labels: feature request
