### ISSUE TITLE
Installation with docker error

### ISSUE THREAD

**Issue by masachi** [tinode/chat#63] opened 2018-01-19 05:24 UTC
I follow your docker installation instruction. When I build initializer image from Dockerfile provided， I get this error "error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function." in "RUN go get -tags rethinkdb github.com/tinode/chat/tinode-db 	&& go install -tags rethinkdb github.com/tinode/chat/tinode-db". And is there any way to solve this? Thank you.

**Comment by or-else** [comment] 2018-01-19 05:42
Hi. Try googling the error message. It seems to be a transient network error on your end. For example, see discussion here: https://github.com/curl/curl/issues/1707
I'll try to reproduce it tomorrow.

**Comment by or-else** [comment] 2018-01-19 16:39
Do you still have this problem?

**Comment by masachi** [comment] 2018-01-20 10:34
I still have the same problem when installing with docker.

**Comment by or-else** [comment] 2018-01-20 16:53
I cannot reproduce it:

```
$ docker --version
Docker version 17.12.0-ce, build c97c6d6

$ docker build --tag=tinode-init-db init-rethinkdb
Sending build context to Docker daemon  4.608kB
Step 1/8 : FROM golang:latest
 ---> 59c0da3fc7cc
Step 2/8 : MAINTAINER Gene Sokolov <gene@tinode.co>
 ---> Running in cf5d741dbddb
Removing intermediate container cf5d741dbddb
 ---> f3400238adbd
Step 3/8 : RUN go get -tags rethinkdb github.com/tinode/chat/tinode-db 	&& go install -tags rethinkdb github.com/tinode/chat/tinode-db
 ---> Running in 7559876a00f4
Removing intermediate container 7559876a00f4
 ---> cddfc759ea32
Step 4/8 : ENV UID_ENCRYPTION_KEY la6YsO+bNX/+XIkOqc5Svw==
 ---> Running in 84226a83a947
Removing intermediate container 84226a83a947
 ---> 4a7b930b8a20
Step 5/8 : COPY config.template /
 ---> 71d16a41f3d1
Step 6/8 : COPY entrypoint.sh /
 ---> 5b3b5120ed20
Step 7/8 : RUN chmod +x /entrypoint.sh
 ---> Running in 7192935e5848
Removing intermediate container 7192935e5848
 ---> 14ed4ea8b330
Step 8/8 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Running in 054f32f8b1a8
Removing intermediate container 054f32f8b1a8
 ---> 85dcea2357b8
Successfully built 85dcea2357b8
Successfully tagged tinode-init-db:latest
```

I'm quite certain that your issue is outside of the scope of this project. 

Try contacting the curl team at the bug I referenced. Try making sure you have a stable network connection. If you are connected to the internet through a proxy, make sure the proxy is not at fault. 

Also see here
https://github.com/git/git-scm.com/issues/717
and here
https://stackoverflow.com/questions/38378914/git-error-rpc-failed-curl-56-gnutls

Do your part please. I'm going to close this issue.

**Closed by or-else** 2018-01-20 16:53 UTC
