### ISSUE TITLE
chatbot.py file not working in python 3.5

### ISSUE THREAD

**Issue by admill1519** [tinode/chat#140] opened 2018-08-28 08:34 UTC
### Subject of the issue
Describe your issue here.

### Is this a bug report of a feature request?
- [ ] Bug report
it is bug report

#### Server-side
- [ ] api.tinode.co
- [ ] Your own setup:
  * platform (Windows Linux etc)
  * version of tinode server, e.g. `0.15.2-rc3`
  * database backend
  
#### Client-side
- [ ] TinodeWeb/tinodejs: javascript client
  * Browser make and version.

- [ ] tn-cli
  * Python version 3.5
- [ ] Chatbot
  * Python version 3.5
- Version of the client, e.g. `0.15.1`

### Steps to reproduce
run chatbot.py file with python 3.5

### Expected behaviour
Should run chatbot file without any error.

### Actual behaviour
Getting following error:

Traceback (most recent call last):
  File "Sony_chatbot.py", line 751, in <module>
    run(args)
  File "Sony_chatbot.py", line 705, in run
    client = init_client(args.host, schema, secret, args.login_cookie)
  File "Sony_chatbot.py", line 168, in init_client
    client_post(login(cookie_file_name, schema, secret))
  File "Sony_chatbot.py", line 126, in login
    return pb.ClientMsg(login=pb.ClientLogin(id=tid, scheme=scheme, secret=secret))
TypeError: '9aanalysisbot:123' has type str, but expected one of: bytes

**Comment by or-else** [comment] 2018-08-28 09:03
Please update the client to the latest. Some fixes were made in https://github.com/tinode/chat/commit/9515159b149106bf7b4397e321d66c990b4ee239. If your bot is pre-June 22nd then it's likely to fail in the way you described it. 

So far I cannot reproduce with the latest chatbot and python 3.6

**Comment by or-else** [comment] 2018-08-28 09:07
And, if you still can reproduce after the upgrade, please tell me what kind of login you are using - 
--login-basic, --login-cookie, --login-token.

**Comment by admill1519** [comment] 2018-08-29 04:52
I am using bot post June 22nd. I am using login type --login-basic

**Comment by or-else** [comment] 2018-08-29 05:43
The line numbers in your stack trace do not match the line numbers in https://github.com/tinode/chat/blob/master/chatbot/chatbot.py which means you are running modified code. I don't see your code so I cat't be sure about what's wrong with it. 

1. If you run unmodified https://github.com/tinode/chat/blob/master/chatbot/chatbot.py, do you see this problem?
2. The immediate reason for the crash is that `secret` is a string when it's expected to be a byte array. In the original code it's converted from the string to bytes in line https://github.com/tinode/chat/blob/master/chatbot/chatbot.py#L259
Do you have an equivalent conversion in your code?
3. You probably incorrectly merged 9515159 or incorrectly modified it after merging.

**Comment by admill1519** [comment] 2018-08-29 11:02
I have made all my changes in client_message_loop function. Not a single line outside of that function

**Comment by admill1519** [comment] 2018-08-29 11:43
python3 chatbot.py --login-basic=9aanalysisbot:123

Traceback (most recent call last):
  File "Sony_chatbot.py", line 24, in <module>
    from pbx import model_pb2 as pb
  File "/home/amol/Pictures/RPA_HR_BOT/pbx/model_pb2.py", line 275, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __new__() got an unexpected keyword argument 'file'

I am getting this error in python 3.6

**Comment by admill1519** [comment] 2018-08-31 09:08
Today I downloaded this repository and executed chatbot file using python 3.5.2 but getting following error. No changes in chatbot file except localhost to my tinode server ip.


C:\Users\Amol\Downloads\chat-master\chat-master\chatbot>python chatbot.py --logi
n-basic=9aflightbot:Flight@12323
Tino, Tinode's chatbot.
Logging in with login:password 9aflightbot:Flight@12323
Loaded 322 quotes
Traceback (most recent call last):
  File "chatbot.py", line 322, in <module>
    run(args)
  File "chatbot.py", line 294, in run
    client_message_loop(client)
  File "chatbot.py", line 175, in client_message_loop
    exec_future(msg.ctrl.id, msg.ctrl.code, msg.ctrl.params)
  File "chatbot.py", line 42, in exec_future
    bundle.get('action')(arg, params)
  File "chatbot.py", line 119, in <lambda>
    'action': lambda fname, params: save_auth_cookie(fname, params),
  File "chatbot.py", line 230, in save_auth_cookie
    nice[key_out] = json.loads(params[key_in])
  File "C:\Program Files\Python35\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by or-else** [comment] 2018-08-31 10:44
So far I cannot reproduce. I'll try installing the same Python version as yours and will try again.

**Comment by or-else** [comment] 2018-08-31 10:47
```
gene$ python3 chatbot.py --login-basic=alice:alice123
Tino, Tinode's chatbot.
Logging in with login:password alice:alice123
Loaded 322 quotes
^CTerminated with signal 2

genes-mbp:chatbot gene$ python3 --version
Python 3.6.5
```

**Comment by admill1519** [comment] 2018-08-31 14:31
I am using 3.5.2. Will that make any difference.

**Comment by or-else** [comment] 2018-08-31 17:30
I can reproduce it now. It's a version dependent bug:
```
genes-mbp:chatbot gene$ python chatbot.py --login-basic=alice:alice123
Tino, Tinode's chatbot.
Logging in with login:password alice:alice123
Loaded 322 quotes
Connecting to server at localhost:6061
Server: b'"mysql:undef"' b'"0.15"'
Traceback (most recent call last):
  File "chatbot.py", line 338, in <module>
    run(args)
  File "chatbot.py", line 310, in run
    client_message_loop(client)
  File "chatbot.py", line 191, in client_message_loop
    exec_future(msg.ctrl.id, msg.ctrl.code, msg.ctrl.text, msg.ctrl.params)
  File "chatbot.py", line 46, in exec_future
    bundle.get('action')(arg, params)
  File "chatbot.py", line 133, in <lambda>
    'action': lambda fname, params: save_auth_cookie(fname, params),
  File "chatbot.py", line 246, in save_auth_cookie
    nice[key_out] = json.loads(params[key_in])
  File "/Users/gene/.pyenv/versions/3.5.2/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
^C
genes-mbp:chatbot gene$ python --version
Python 3.5.2
```

I'll fix it with the next rc.

**Comment by or-else** [comment] 2018-08-31 17:56
I pushed the change which fixes the problem https://github.com/tinode/chat/commit/1f3912b29585d0e62b8d2d0a48fcbc03cf9fffa6. I'll merge it to devel and release v0.15.5-rc6.

If you don't want to wait for the merge just do this:
```
-        nice[key_out] = json.loads(params[key_in])
+        nice[key_out] = json.loads(params[key_in].decode('utf-8'))
```

**Comment by or-else** [comment] 2018-09-01 08:12
I pushed the updated docker images v0.15.5rc6

**Comment by admill1519** [comment] 2018-09-04 07:09
Thanks, let me check and get back to you.

**Comment by or-else** [comment] 2018-09-04 07:39
The grpc bindings are now shipped as a package `tinode-grpc` https://pypi.org/project/tinode-grpc/

See updated docs https://github.com/tinode/chat/tree/master/chatbot

**Comment by or-else** [comment] 2018-09-11 15:36
Any update on this?

**Comment by or-else** [comment] 2018-09-13 16:26
There was no update in more than a week. I assume everything is fine or no longer relevant. Closing.

**Closed by or-else** 2018-09-13 16:26 UTC
Labels: bug
