### ISSUE TITLE
is a plan on  Support voice call and video call.

### ISSUE THREAD

**Issue by mmszhezhi** [tinode/chat#568] opened 2020-11-18 06:13 UTC
**If you are not requesting a feature, please post to https://groups.google.com/d/forum/tinode instead.**
---

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by or-else** [comment] 2020-11-18 19:20
Duplicate of https://github.com/tinode/chat/issues/150

**Closed by or-else** 2020-11-18 19:20 UTC
Labels: feature request
