### ISSUE TITLE
How to search by username?

### ISSUE THREAD

**Issue by pwFoo** [tinode/chat#243] opened 2019-06-08 11:13 UTC
Hi @or-else 
Searching contacts by `email:<address>` or tag `<tag_name>` works fine. `tel:<number>` isn't allowed and would be critical without verification, but how to search for an username?

Best way would be just typing the username without any prefix like `tel:` or `email:`?

**Comment by or-else** [comment] 2019-06-08 15:15
`basic:alice`

**Comment by pwFoo** [comment] 2019-06-08 15:51
Could you add the basic prefix to the placeholder text and some more usage information to documentation? Or change behavior to search usernames without `basic:` prefix and add `tag:` as prefix for tags?

**Comment by pwFoo** [comment] 2019-06-28 14:22
Or would it possible to detect type? regex detection for email addresses and phone numbers? Search username without prefix instead of "basic:" because username should be default?
Tags could have the prefix "tag:" if username works without prefix?

**Comment by or-else** [comment] 2019-06-28 17:12
It's certainly possible to detect emails & phone numbers and automatically prefix them with email: and tel:. It's not so easy with logins. Maybe the search form could be a bit more cmplex and ask the user if search is by user name. Or maybe all non-email and non-phone tags can be send in two versions, with basic: and without.

**Comment by kyktommy** [comment] 2019-08-19 02:32
How to search for user's public? I only get "basic:usr" with { get } tags, but I want to get photo inside public fn.

**Comment by or-else** [comment] 2019-08-19 13:20
It's not searchable by design. If you want to search it too, you need to copy it to tags.

**Comment by vapao** [comment] 2019-10-25 02:25
@pwFoo I think all you need is to add a user name to `{acc: tags}` when you create an account. So it can search by username.

**Comment by or-else** [comment] 2019-10-25 03:35
Search for `basic:username`. I.e. `basic:alice`.

**Comment by or-else** [comment] 2019-10-25 03:36
And yes, you can add a username to account tags if you want to be found by username.

**Comment by curiousgeek123** [comment] 2020-03-27 16:07
@or-else  Is there a way to add tool tips along with each field  or some info on top so that layman users can know that if they put something in tags, then they will be searchable.

Also, i think it would be nice to allow user search by username/user ID directly in the search field of users without any prefix, is this possible?

**Comment by or-else** [comment] 2020-03-27 17:34
>  is this possible?

Yes, it is possible. Would you like to help implementing the feature?

**Comment by or-else** [comment] 2020-07-07 16:19
Released in 0.16.7-rc1

**Comment by or-else** [comment] 2020-07-19 03:19
All released.

**Closed by or-else** 2020-07-19 03:19 UTC
Labels: feature request
